@startuml

	class Member {
		-memberId
	}
	
	class MembersDao {
		+create(member)
		+delete(memberId)
		+updateMember(member)
		+getAll()
	}
	
	class CreateMemberController {
		createMember(member)
	}

	class MembersManagementView {
		+MembersManagementView()
		+createMember()
	}

	class CreateMemberDialog { 
		+CreateMemberDialog()
		setName(name)
		setRoles(roles)
		confirm()
		cancel()
	}
	 
	MembersDao .left.> Member
	CreateMemberController .up.> MembersDao
	CreateMemberController .up.> Member
	CreateMemberController <-- CreateMemberDialog
	MembersManagementView .up.> Member
	MembersManagementView -right-> CreateMemberDialog
	CreateMemberDialog .up.> Member
	
	
@enduml
