@startuml
    state 0 as "OPENED_DISCIPLINES"
    state 1 as " "
    state 4 as " "
    state 5 as " "
    state 6 as " "
    state 7 <<choice>>
    state 8 as " "
    state 9 as " "
    state 13 as " "
    state 14 as " "
    state 15 as " "
    state 16 as " "
    state 11 <<choice>>
    state 12 as "OPENED_DISCIPLINES"

    0 --> 1
    note on link
        Manager orders assign chip/pill
    end note
    1 --> 13
    note on link
        System shows
        **  1 column for each member schedule until end of current iteration
        **  1 column for each discipline and inside
        *** assignable (1 hour) chips/pills
        System allows
        ** select chip/pill from [ ] to assign
        *** member schedule column
        *** specific discipline column

    end note
    13 --> 11
    note on link
        Manager introduces
         * chip/pill to assign
    end note
    11 --> 4
    11 --> 5 : [pill not assigned to member]
    4 --> 14
    note on link
        System allows
        * introduce assign destination
        ** another member
        ** chip belonging discipline column
        * request close activity
    end note
    14 -down-> 15
    note on link
        Member introduces
        * assign destination another member
    end note
    14 -down-> 16
    note on link
        Member introduces
        * assign destination chip belonging discipline column
    end note
    15 --> [*]
    note on link
        System shows
        * the pill re-assigned to another member
    end note
    16 --> [*]
    note on link
        System shows
        * the pill re-assigned in the top of his discipline column
    end note
    5 --> 6
    note on link
        System allows
        * introduce pill assign destination
        ** specific member schedule (specific hour in member column)
        * request re-estimate activity
        * request split selected activity
        * request "fundir" activity
    end note
    6 --> 7
    note on link
    Manager introduces
    * member schedule datetime (inside the actual iteration limits)
    end note
    7 --> 8
    note on link
        [pill to assign overlaps with the member schedule assigned pills
            OR
        member assigned activities durations > member max capacity in actual iteration]
    end note
    8 --> 5
    note on link
         System shows error
         * the destination (datetime) is invalid
    end note
    7 --> 9
    9 --> 12
    note on link
        System
        * Hides the selected pill from his specific discipline
        * Shows the selected pill in member schedule
    end note
@enduml
