@startuml

    state 0 as "OPENED_PROJECT"
    state 1  <<choice>>
    state 2 as "USE_CASES_MANAGEMENT"
    state 3 as "MEMBERS_MANAGEMENT"
    state 4 as " "
    state 5 as " "
    state 6 as " "


    0 --> 1
        note "(si vacia, selecciona casos de uso \n y hasta donde quiere llegar del ucase generar pastillas \n actividades no ligadas a caso de uso 1h, las de caso de uso si se quiere \n llegar a ese nv de disciplina)" as N1
    2 --> 1
    note on link
        Manager orders open disciplines
    end note
    3 --> 1
    1 --> 4
    note on link
        [empty iteration]
    end note
    4 --> 6
    note on link
        * System shows
        ** priorized usecases
        * Allows
        ** "specify" use case desired progress / scope
        *** REQUIREMENTS | ANALYSIS | DESIGN | IMPLEMENTATION
    end note
    6 --> 5
    note on link
    * Manager introduces use cases desired scope
    * And orders confirm open iteration
    end note
    1 --> 5
    note on link
        [Iteration opened]
    end note
    5 --> [*]
    note on link
     * System shows information
     ** each member schedule until end of current iteration
     ** discipline containers
     ** assignable discipline 1 hour chips "pastillas" (pills)
     * Allows
     ** split activity
     ** assign activity to member schedule
     ** re-estimate activity
     ** Merge activity
     ** Open project
     ** Open members
    end note
@enduml
