@startuml

    state 0 as "OPENED_PROJECT"
    state 1 as " "
    state 2 as "USE_CASES_MANAGEMENT"
    state 3 as "MEMBERS_MANAGEMENT"

    0 --> 1
    2 --> 1 : Manager orders open disciplines
    3 --> 1
    1 --> [*] : System shows each member schedule (column with datatime since end of current iteration) , \n AND shows discipline containters and assignable discipline 1 hour chips "pastilla" (pills) \n AND System allows split activity \n   assign activity to member schedule \n   re-estimate activity \n   "fundir" activity \n   Open project \n   Open members


@enduml
