@startuml

state 1 as " "
state 2 as " "
state 3 <<choice>>
state 4 as " "
state 5 as " "

[*] --> 1
note on link
    User orders plan project
end note
1 --> 2
note on link
    * System allows introduce
    ** start project date
    ** end project date
    ** project cost
end note
2 --> 3
note on link
    * User introduces
    ** start date
    ** end date
    ** project cost
    * and orders continue
end note
3 --> 1
note on link
    * [end date before start date
    * OR start date after end date
    * OR cost <= 0
    * OR start end date interval < 10 days]
end note
3 --> 4
4 --> 5
note on link
    * System shows information
    ** nº iterations in project (10 iterations by default)
    ** iteration duration (in days)
    **each phase start end dates
    * allows
    ** change nº iteration in project
    *** [ +/- 10 iterations ]
    ***[ minimum 10 iteration in project ]
    ***(minimum iteration duration 10 days)
    ** confirm planned project
end note
5 --> 4
note on link
    * User introduces new nº of iterations
    * and orders re-plan
end note
5 --> [*]
note on link
    User order confirm planned project
end note
@enduml
