@startuml

state 1 <<choice>>
state 2 as " "
state 3 as " "

[*] --> 1 : User opens the app
1 --> 2 : [project not planned]
1 --> 3  : [project planned]
2 --> [*]
    note on link
    * System allows plan project
    end note
3 --> [*]
    note on link
        * System shows project information
        **(detallar project information)
        * Allows:
        ** open phases
        ** open iterations
        ** open iteration
        ** open use cases
        ** open members
    end note
@enduml
