@startuml
!include ../StateDiagramsSetUp.puml

USE_CASE_MANAGEMENT ---> CreateUseCase

state CreateUseCase {

    'Main path
    [*] --> Form
    note on link
        <b>User request</b>
        * to create a use case
    end note

    note right of Form
      <b>Fields</b>
      * name [required] [unique] [length > 5 && < 25 ]
      * description [optional] [length > 5 && < 200 ]
    end note

    Form --> SaveConfirmation

    SaveConfirmation --> OpenUseCases

    OpenUseCases --> [*]
}

CreateUseCase --> USECASES_MANAGEMENT
    note on link
    <b>System allows</b>
    * prioritize usecases
    * create usecase
    * update usecase
    * delete usecase
    * open iterations
    * open iteration
    * open members
    end note

@enduml
