@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
        ArrowColor #green
        NoteBorderColor #green
    }

state init as "USE_CASE_MANAGEMENT"
state end as "USE_CASE_MANAGEMENT"

init ---> DeleteUseCase
DeleteUseCase ---> end
note on link
<b>System allows</b>
* create member
* update member
* delete member
* open project
* open iteration
* open use cases
end note

state DeleteUseCase {
    state initial as " "
    state deleteOrdered as " "
    state confirmationRequired <<choice>>
    state deleteConfirmed as " "
    state askedForWhichOneDelete as " "
    state showList as " "

    'Main path
    [*] --> initial
    note on link
        <b>User request</b>
        * delete a use case
    end note
    initial --> askedForWhichOneDelete
    note on link
    <b>System shows</b>
    * all use cases
    <b>System require</b>
    * A use case to delete
    end note
    askedForWhichOneDelete --> deleteOrdered
    note on link
        <b>User provide</b>
        * the use to delete
    end note
    deleteOrdered --> confirmationRequired
    note on link
        <b>System allows</b>
        * confirm
        * cancel
    end note
    confirmationRequired --> deleteConfirmed
        note on link
            <b>User request</b>
            * confirm to delete the use case
        end note
    deleteConfirmed --> showList
    note on link
    <b>System shows</b>
    * the use case has been deleted
    end note
    showList --> [*]
    note on link
    <b>System shows</b>
    * use case list
    end note

    'Variation path
    confirmationRequired -[#red]-> showList
    note on link
        <b>User request</b>
        * cancel
    end note
}

@enduml
