@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
        ArrowColor #green
        NoteBorderColor #green
    }
    state 0 as ":PROJECT_MANAGEMENT"
    state 2 as ":MEMBERS_MANAGEMENT"
    state 3 as ":DISCIPLINES_MANAGEMENT"

    0 --> OpenUsecases

    2 --> OpenUsecases


    3 --> OpenUsecases

state OpenUsecases{

    [*] --> [*]
        note on link
            User requests to open usecases
        end note
}

OpenUsecases --> USECASES_MANAGEMENT
    note on link
        <b>System shows</b>
        * all use cases sorted by priority
        ** highest priority in the top, lowest in the button
        ** use case without priority has the lowest priority
        <b>System allows</b>
        * prioritize usecases
        * create usecase
        * update usecase
        * delete usecase
        * open iterations
        * open iteration
        * open members
    end note

@enduml
