@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
        ArrowColor #green
        NoteBorderColor #green
    }
    state 0 as ":PROJECT_MANAGEMENT"
    state 2 as ":MEMBERS_MANAGEMENT"
    state 3 as ":DISCIPLINES_MANAGEMENT"

    0 --> OpenUsecases

    2 --> OpenUsecases


    3 --> OpenUsecases

state OpenUsecases{

    [*] --> [*]
        note on link
            User requests to open usecases
        end note
}

OpenUsecases --> ShowUseCases

@enduml
