@startuml
skinparam NoteBackgroundColor #whiteSmoke


'Initial/end states
state init as "USE_CASE_MANAGEMENT"
state end as "USE_CASE_MANAGEMENT"

init ---> UpdateUseCase
UpdateUseCase ---> end
note on link
<b>System allows</b>
* create member
* update member
* delete member
* open project
* open iteration
* open use cases
end note

'Use case specfication
state UpdateUseCase {
    state updateOrdered as " "
    state requiredUseCaseToUpdate as " "
    state selectedUseCase as " "
    state editUseCase as " "
    state editedUseCase  <<choice>>
    state requireToConfirm  as " "
    state savedUseCase as " "
    state errorValidation as " "

    'Main path
    [*] --> updateOrdered
    note on link
        <b>User request</b>
        * to update a use case
    end note
    updateOrdered --> requiredUseCaseToUpdate
    note on link
        <b>System require</b>
        * The use case to be updated
    end note
    requiredUseCaseToUpdate --> selectedUseCase
    note on link
        <b>User provide</b>
        * The use case to update
    end note
    selectedUseCase --> editUseCase
    note on link
        <b>System shows</b>
        * use case name
        <b>System require</b>
        * use case name
    end note
    editUseCase --> editedUseCase
    note on link
        <b>User provide</b>
        * name
    end note
    editedUseCase --> toConfirm
    toConfirm --> requireToConfirm
            note on link
            <b>System allow</b>
            * confirm
            * cancel
            end note
    requireToConfirm --> savedUseCase
        note on link
        <b>User</b> confirm
        end note
    savedUseCase --> [*]
           note on link
           <b>System shows</b>
           * the use case list
           end note

    'variation path
    editedUseCase --> errorValidation
        note on link
        [ length(useCaseName) out of 5,25 ]
        end note

    errorValidation --> selectedUseCase
            note on link
            <b>System shows</b>
            * The name length is not correct
            end note

    'variation path
    requireToConfirm --> savedUseCase
    note on link
          <b>User</b> cancel
    end note
}

@enduml
