@startuml
left to right direction

actor "User" as user

package General {
:user: -down-> (startSystem)
:user: -down-> (closeSystem)
:user: -down-> (OpenProject)
:user: -down-> (openPhases)
:user: -down-> (openIterations)
:user: -down-> (PlanProject)
:user: -down-> (CloseIteration)
}

package Members {
:user: -down-> (OpenMembers)
:user: -down-> (CreateMember)
:user: -down-> (UpdateMember)
:user: -down-> (DeleteMember)
}

package UseCases {
:user: -left-> (OpenUseCases)
:user: -left-> (CreateUseCase)
:user: -left-> (DeleteUseCase)
:user: -left-> (UpdateUseCase)
:user: -left-> (PrioritizeUseCases)
}

package Disciplines {
:user: -left-> (OpenIteration)
:user: -left-> (AssignActivity)
:user: -left-> (Re-estimateActivity)
:user: -left-> (SplitActivity)
:user: -left-> (CloseActivity)
:user: -left-> (MergeActivity)
}
@enduml
