@startuml
left to right direction

actor "User" as user

package general {
    :user: -left--> (startSystem)
    :user: -left--> (closeSystem)
    :user: -left--> (OpenProject)
    :user: -left--> (openPhases)
    :user: -left--> (openIterations)
    :user: -left--> (PlanProject)
    :user: -left--> (CloseIteration)
}

package members {
    :user: -up-> (OpenMembers)
    :user: -up-> (CreateMember)
    :user: -up-> (UpdateMember)
    :user: -up-> (DeleteMember)
}

package usecases {
    :user: -right-> (OpenUseCases)
    :user: -right-> (CreateUseCase)
    :user: -right-> (DeleteUseCase)
    :user: -right-> (UpdateUseCase)
    :user: -right-> (PrioritizeUseCases)

    (CreateUseCase) ..> (OpenUseCases)
    (DeleteUseCase) ..> (OpenUseCases)
    (UpdateUseCase) ..> (OpenUseCases)
    (PrioritizeUseCases) ..> (OpenUseCases)

}

package disciplines {
    :user: -down-> (OpenIteration)
    :user: -down-> (AssignActivity)
    :user: -down-> (Re-estimateActivity)
    :user: -down-> (SplitActivity)
    :user: -down-> (CloseActivity)
    :user: -down-> (MergeActivity)
}

package shared {
    (DeleteConfirmation)
    (SaveConfirmation)

    (DeleteUseCase) ..> (DeleteConfirmation)
    (DeleteMember) ..> (DeleteConfirmation)

    (CreateUseCase) ..> (SaveConfirmation)
    (CreateMember) ..> (SaveConfirmation)

    (UpdateUseCase) ..> (SaveConfirmation)
    (UpdateMember) ..> (SaveConfirmation)
}

@enduml
