@startuml
!procedure _updateUsecaseUI()
{^"Use case 1"
    {+
        {^"Update use case"
          usecase    | "plan Project            "
        }
        {+ [<&plus> Save] | [<&x> Cancel]}
    }
}
!endprocedure
@enduml