@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user
boundary IterationView
boundary ConfirmDialog
control MergeActivityController
entity ActivitiesDao

user -right-> IterationView
    note on link
        mergeActivity(activityId)
    end note
user -down-> ConfirmDialog
    note on link
        confirm()
        cancel()
    end note

IterationView --> ConfirmDialog
    note on link
        new ConfirmDialog()
    end note

IterationView -right-> MergeActivityController
    note on link
        merge(activityId)
    end note
MergeActivityController -right-> ActivitiesDao
    note on link
        delete(activityId)
    end note

@enduml
