@startuml

actor user

boundary InitProjectView
control StartSystemController

entity Project
entity ProjectDao

user --> InitProjectView
    note on link
        openApp()
    end note
InitProjectView -right-> StartSystemController
    note on link
        getProject()
    end note
StartSystemController -right-> ProjectDao
    note on link
        getProject()
    end note

InitProjectView -down-> Project
StartSystemController .down.> Project
ProjectDao ..> Project
@enduml
