@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

skinparam linetype polyline

actor user

view IterationsView
view PhasesView

controller OpenIterationsController

model Phase
model Iteration
model PhaseDao

user -right-> PhasesView
    note on link
        openPhase(phaseId)
    end note

PhasesView -down-> IterationsView
note on link
    new IterationsView(phaseId)
end note
IterationsView -right-> OpenIterationsController
    note on link
        getPhase(phaseId)
    end note

OpenIterationsController ..> Phase
OpenIterationsController -right-> PhaseDao
    note on link
        getPhase(phaseId)
    end note

IterationsView -> Phase
IterationsView .> Iteration
Phase o--> Iteration
PhaseDao ..> Phase
@enduml
