@startuml

  set namespaceSeparator .
  title "Clases a Crear"

  ModelClass <.. "based" Artifacts.UseCaseView
  ModelClass <.. "based" Artifacts.DomainModel
  ViewClass "1" <-- "1" Actor
  ViewClass "1" <-- "1" ModelClass
  ControllerClass "1" <-- "1" UseCase

  note "Clases independientes de la tecnologia" as N2

@enduml