@startuml

top to bottom direction

namespace Artifacts {
    Class Artifact

    Abstract Class ArtifactVersion
    Class ArtifactTemplate extends ArtifactVersion

    '4+1 vistas
    Class DomainModel extends ArtifactVersion
    Class UseCaseView extends ArtifactVersion
    Class DesignView extends ArtifactVersion
    Class ImplementationView extends ArtifactVersion
    Class ProcessView extends ArtifactVersion
    Class DeployView extends ArtifactVersion
    

    Class TestModel extends ArtifactVersion
    
    Class ArquitectureDesign extends ArtifactVersion

    Class UMLDiagram extends ArtifactVersion
    

    Class NormasCalidad extends ArtifactVersion
    Class Metricas extends ArtifactVersion
    Class ProjectManagementAndConfiguration extends ArtifactVersion
    
    Artifact *-- "0..*" ArtifactVersion
    ArtifactVersion o-- "0..*" ArtifactVersion

    Class Requisitos extends ArtifactVersion
      Requisitos *-up- "1..*" RequisitoFuncional
    Class RequisitosSuplementarios extends ArtifactVersion
      RequisitosSuplementarios *-up- "1..*" RequisitoNoFuncional
    Abstract Class Requisito
    Class RequisitoNoFuncional extends Requisito
    Class RequisitoFuncional extends Requisito
    Class RequisitosSuplementarios extends ArtifactVersion
    
    
    Class ListaCaracteristicas extends ArtifactVersion 
    ListaCaracteristicas *-- "1..*" Caracteristicas
    Class Caracteristicas {
        Estado
        Definicion
        CosteEstimado
        Prioridad
        NivelRiesgo
    }
    Class Glosary extends ArtifactVersion

    Class ArquitectureDescription extends UseCaseView
    Class DetalledUseCase extends UseCaseView
    Class StructuredUseCase extends DetalledUseCase

    Class AnalisysArquitectureDescription extends UseCaseView
    Class AnalisysPackageDiagramDraft extends PackageDiagram
    Class AnalisysClassDiagramForUseCases extends ClassDiagram
    Class AnalisysClassDiagramDraft extends ClassDiagram

    Class UIPrototype extends ArtifactVersion

    Class SourceCode extends ArtifactVersion
    Class Executable extends ArtifactVersion


    'TODO: Diagrama, PDF 1.Introducion hoja 22
    'TODO: Diagrama, PDF 1.Introducion hoja 47

    'TODO: Elementos de Entrega interna y entrega externa
}

@enduml