@startuml
	class CloseActivityController {
	+close(activity)
	}

	CloseActivityView --> CloseActivityController
	CloseActivityController --> ActivitiesDao
	CloseActivityController ..> Activity
@enduml
