@startuml
	class Iteration {
	}

	IterationsView o..> Iteration
	ShowIterationController ..> Iteration
	OpenIterationController ..> Iteration
	IterationDao ..> Iteration
	IterationView --> Iteration
@enduml
