@startuml
 skinparam linetype polyline

namespace controllers {
    namespace controllers.projectmanagement {
        class StartSystemController
        class CloseSystemController
        class PlanProjectController
        class OpenPhasesController
        class OpenIterationsController
        class OpenIterationController
        class AssignActivityController
        class RestimateActivityController
        class MergeActivityController
        class SplitActivityController
        class CloseActivityController
    }
    namespace controllers.members {
        class OpenMembersController
        class CreateMemberController
        class UpdateMemberController
        class DeleteMemberController
    }
    namespace controllers.usecases {
        class OpenUseCasesController
        class CreateUseCaseController
        class UpdateUseCaseController
        class DeleteUseCaseController
        class PrioritizeUseCaseController
    }
}

newPage

namespace views {
    class MenuView
    namespace views.shared {
        interface Dialog
        interface ConfirmationDialog
    }
    namespace views.projectmamagement {
        class ProjectManagementView
        class InitProjectView
        class PlanProjectView
        class IterationView
        class PhaseView
        class AssignActivityView implements views.shared.Dialog
        class CloseActivityView implements views.shared.ConfirmationDialog

        ProjectManagementView ..> PhaseView
        PhaseView --> IterationView
        IterationView ..> CloseActivityView
    }
    namespace views.members {
        class MembersManagementView
        class CreateMemberView implements views.shared.Dialog
        class UpdateMemberView implements views.shared.Dialog
        class DeleteMemberView implements views.shared.ConfirmationDialog

        MembersManagementView ..> DeleteMemberView
        MembersManagementView ..> CreateMemberView
        MembersManagementView ..> UpdateMemberView
    }
    namespace views.usecases {
        class UseCasesManagementView
        class CreateUseCaseView implements views.shared.Dialog
        class UpdateUseCaseView implements views.shared.Dialog
        class DeleteUseCaseView implements views.shared.ConfirmationDialog

        UseCasesManagementView ..> DeleteUseCaseView
        UseCasesManagementView ..> CreateUseCaseView
        UseCasesManagementView ..> UpdateUseCaseView
    }

    views.MenuView ..> views.projectmamagement.ProjectManagementView
    views.MenuView ..> views.members.MembersManagementView
    views.MenuView ..> views.usecases.UseCasesManagementView
}

newPage

namespace model {
    class Member
    class UseCase
    class Iteration
    Class Activity
    class Project
    class Phase
    class Discipline
    
    Iteration *-> Member
    Iteration *-> Activity
    
    Member *--> Activity
    Activity --> Discipline
    Activity --> UseCase
    Phase *--> Iteration
    Project *--> Phase
}

@enduml
