@startuml


package controllers {
    class StartSystemController
    class CloseSystemController
    class PlanProjectController
    class OpenPhasesController
    class OpenIterationsController
    class OpenIterationsController
    class AssignActivityController
    class ReestimateActivityController
    class MergeActivityController
    class SplitActivityController
    class CloseActivityController
    class OpenMembersController
    class CreateMemberController
    class UpdateMemberController
    class DeleteMemberController
    class OpenUseCasesController
    class CreateUseCaseController
    class UpdateUseCaseController
    class DeleteUseCaseController
    class PrioritizeUseCasesController
}

package views {
    interface Dialog
    interface ConfirmationDialog

    class IterationView
    class AssignActivityView
    class CloseActivityView
    class InitProjectView
    class PlanProjectView
    class ProjectManagementView
    class PhaseView
    class MembersManagementView
    class CreateMemberView
    class UpdateMemberView
    class DeleteMemberView
    class UseCasesManagementView
    class CreateUseCaseView
    class UpdateUseCaseView
    class DeleteUseCaseView

    Dialog <|.. AssignActivityView
    Dialog <|.. CreateMemberView
    Dialog <|.. UpdateMemberView
    Dialog <|.. CreateUseCaseView
    Dialog <|.. UpdateUseCaseView

    ConfirmationDialog <|.. CloseActivityView
    ConfirmationDialog <|.. DeleteMemberView
    ConfirmationDialog <|.. DeleteUseCaseView

}

package model {
    class Member
    class UseCase
    class Iteration
    Class Activity
    class Project
    class Phase
}

@enduml
