@startuml

namespace controllers {
    class StartSystemController
    class CloseSystemController
    class PlanProjectController
    class OpenPhasesController
    class OpenIterationsController
    class OpenIterationController
    class AssignActivityController
    class ReestimateActivityController
    class MergeActivityController
    class SplitActivityController
    class CloseActivityController
    class OpenMembersController
    class CreateMemberController
    class UpdateMemberController
    class DeleteMemberController
    class OpenUseCasesController
    class CreateUseCaseController
    class UpdateUseCaseController
    class DeleteUseCaseController
    class PrioritizeUseCasesController
}

namespace views {
    interface Dialog
    interface ConfirmationDialog

    class MenuView
    class ProjectManagementView
    class MembersManagementView
    class UseCasesManagementView

    class InitProjectView
    class PlanProjectView
    class IterationView
    class PhaseView

    class AssignActivityView implements Dialog
    class CreateMemberView implements Dialog
    class UpdateMemberView implements Dialog
    class CreateUseCaseView implements Dialog
    class UpdateUseCaseView implements Dialog

    class DeleteUseCaseView implements ConfirmationDialog
    class CloseActivityView implements ConfirmationDialog
    class DeleteMemberView implements ConfirmationDialog
    
    MenuView ..> ProjectManagementView
    MenuView ..> MembersManagementView
    MenuView ..> UseCasesManagementView
    
    ProjectManagementView ..> PhaseView
    PhaseView --> IterationView
    
    MembersManagementView ..> DeleteMemberView
    MembersManagementView ..> CreateMemberView
    MembersManagementView ..> UpdateMemberView
    
    UseCasesManagementView ..> DeleteUseCaseView
    UseCasesManagementView ..> CreateUseCaseView
    UseCasesManagementView ..> UpdateUseCaseView

    IterationView ..> CloseActivityView
}

namespace model {
    class Member
    class UseCase
    class Iteration
    Class Activity
    class Project
    class Phase
    class Discipline
    
    Iteration *-> Member
    Iteration *-> Activity
    
    Member *--> Activity
    Activity --> Discipline
    Activity --> UseCase
    Phase *--> Iteration
    Project *--> Phase
}

namespace helpers {
    class TimeInterval
}

@enduml
