@startuml
!include ../StateDiagramsSetUp.puml

state 4 as ":INIT_PROJECT"

[*] --> StartSystem
note on link
    User opens the app
end note

state StartSystem {
    state 5 as " "
    state 2 <<choice>>

    [*] --> 2

    2 --> [*]

    2 --> 5
    note on link
    [exists planned project]
    end note

    5 --> [*]
    note on link
    <b>System shows</b>
    * project information
    ** start date
    ** end date
    ** duration (business days)
    ** progress (business days)
    ** iteration duration (business days)
    <b>System allows</b>
    * open phases
    end note
}

StartSystem --> 4
    note on link
    <b>System allows</b>
    * plan project
    * close system
    end note
@enduml
