@startuml

state 1 as " "
state 2 as " "
state 3 <<choice>>
state 6 as " :USECASE_MANAGEMENT"

[*] --> 1 : Manager request create use case
1 --> 2 : System allows to input usecase name
2 --> 3 : Manager introduce usecase name and order create use case
3 --> 2 : [empty usecase name \n OR usecase name already exists]
3 --> 6
@enduml
