@startuml

state 1 <<choice>>
state 2 as " "
state 3 as " "

[*] --> 1 : Manager opens the app
1 --> 2 : [project not planned]
1 --> 3  : [project planned]
2 --> [*] : System allows plan project
3 --> [*] : System shows the project information \n AND allows user change zoom \n AND allows refresh the project \n AND allows open use Cases view \n AND allows open resources \n AND allows open iteration
@enduml
