@startuml

top to bottom direction
skinparam Linetype ortho

namespace Resources {
    
'Objects
Class Resources.Team
Class Resources.JornadaLaboral {
    WorkingHoursDays
    WorkingDaysMonth
'   VolumenDeHoras
}
Class Resources.Rol
Class Resources.Member {
    ContractType
    Cost
}

Resources.Team *-down- "1..*" Resources.Member
Resources.Member *-- "0..*" Resources.Rol : skills
Resources.Member *-- "1" Resources.JornadaLaboral
}

@enduml
