@startuml
	class UpdateUseCaseController {
	+updateUseCase(useCase)
	}

	UpdateUseCaseDialog --> UpdateUseCaseController
	UpdateUseCaseController ..> UseCase
	UpdateUseCaseController --> UseCaseDao
@enduml
