@startuml 

skinparam {
    NoteBackgroundColor #whiteSmoke
    StateBackgroundColor #green
}

(*) --> "<img:https://share.balsamiq.com/c/m8ZYkthpBqcxEXcjKaZuHk.png>" as memberManagement #LawnGreen
    note on link
        openMembers
    end note

memberManagement --> "<img:https://share.balsamiq.com/c/7aJRpBgnz4N7WsgLdi3hZ7.png>" as createMemberUI
note on link
    create member
end note

memberManagement --> "<img:https://share.balsamiq.com/c/btEKp7cr1fhW4R21ZW5xnc.png>" as deleteMemberUI
note on link
    delete member
end note

memberManagement --> "<img:https://share.balsamiq.com/c/m6SaY4badmmHRonaNua71p.png>" as updateMemberUI
note on link
    update member
end note
@enduml