@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
    StateBackgroundColor #green
}

(*) --> "<img:https://share.balsamiq.com/c/gViP8S2Mu926xNmkKzMXp9.png>" as usacasesManagement #LawnGreen
note on link
    openUsecases
end note


usacasesManagement --> "<img:https://share.balsamiq.com/c/mtCBbTkSqcrP9tr4TC1sg6.png>" as createUsecase
note on link
    create usecase
end note

usacasesManagement --> "<img:https://share.balsamiq.com/c/i75aDY9RXfxsqjkSvGAy8P.png>" as deleteUsecase
note on link
    delete usecase
end note

usacasesManagement --> "<img:https://share.balsamiq.com/c/rNCGG3X8q7y4uckZTpmdN2.png>" as updateUsecase
note on link
    update usecase
end note

usacasesManagement --> "<img:https://share.balsamiq.com/c/3Dt74XPi2QoyBPuNYfEuxg.png>" as  prioritizeUseCases
note on link
 prioritize Usecases
end note
@enduml


