@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view IterationView
view AssignActivityView
view ConfirmDialog
controller OpenIterationController
controller AssignActivityController
model Iteration
model MemberDao
model ActivityDao
model TimeInterval
model Activity
model Member
user -right-> IterationView
note on link
assignActivity()
end note

user -> ConfirmDialog
note on link
confirm()
cancel()
end note


user -right-> AssignActivityView
note on link
setActivity(activity)
setMember(member)
setTimeInterval(timeInterval)
end note
IterationView -down-> AssignActivityView
note on link
new AssignActivityView()
end note
IterationView -down-> OpenIterationController
note on link
    getIteration(currentIteration)
end note
OpenIterationController -down-> Iteration
note on link
    getIteration(currentIteration)
end note
AssignActivityView -right-> AssignActivityController
note on link
    assignActivity(activity, member, timeInterval)
end note
AssignActivityView -down-> ConfirmDialog

Iteration *-right-> ActivityDao
Iteration *-right-> MemberDao
Iteration *-right-> TimeInterval
MemberDao *--> Member
ActivityDao *--> Activity

AssignActivityController --> Activity
note on link
updateActivity(activity)
end note

Activity o-- TimeInterval
Activity o-- Member



@enduml
