@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view IterationView
view CloseActivityView
controller CloseActivityController
model Activity
model ActivitiesDao

user -right-> IterationView
note on link
    closeActivity(activityId)
end note

user -down-> CloseActivityView
note on link
    setRealDuration(numberOfHours)
end note

IterationView -down-> CloseActivityView
note on link
    new CloseActivityView()
end note

CloseActivityView -right-> CloseActivityController
note on link
    close(activity)
end note

CloseActivityController -down-> ActivitiesDao
note on link
    patch(activity)
end note

CloseActivityView --> Activity
CloseActivityController --> Activity
@enduml
