@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view IterationView
view CloseActivityView
view ConfirmDialog
controller OpenIterationController
controller CloseActivityController
model Iteration
model Activity
model ActivitiesDAO

user -right-> IterationView

note on link
closeActivity()
end note
user -down-> CloseActivityView
note on link
confirm()
cancel()
end note
CloseActivityView -left-> ConfirmDialog

IterationView -down-> CloseActivityView
note on link
new CloseActivityView()
end note

IterationView -down--> OpenIterationController
note on link
    getIteration(currentIteration)
end note


CloseActivityView -down-> CloseActivityController
note on link
    CloseActivity(activity)
end note

CloseActivityController -down-> ActivitiesDAO
note on link
updateActivity(activity)
end note

OpenIterationController -down-> Iteration
note on link
    getIteration(currentIteration)
end note

Iteration *-down- Activity
ActivitiesDAO *-right- Activity


@enduml