@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view MembersManagementView
view CreateMemberDialog
view ConfirmDialog
controller CreateMemberController
controller OpenMembersController
model MembersDAO
model Member

user -right-> MembersManagementView
note on link
createMember()
end note
user -right-> CreateMemberDialog
note on link
setName(name)
setRoles(roles)
confirm()
cancel()
end note
MembersManagementView -down-> CreateMemberDialog
note on link
new MemberDialog()
end note
CreateMemberDialog -down-> ConfirmDialog
note on link
new ConfirmDialog()
confirm()
cancel()
end note
CreateMemberDialog -right-> CreateMemberController
note on link
 createMember(member)
end note
CreateMemberDialog -right-> Member
note on link
new Member()
end note
MembersManagementView -right-> OpenMembersController
note on link
readMembers()
end note
CreateMemberController -right-> MembersDAO
note on link
create(member)
end note
CreateMemberController -down- Member
OpenMembersController -down-> MembersDAO
note on link
readMembers()
end note
MembersDAO *-down- Member

@enduml