@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view MembersManagementView
view DeleteMemberDialog
view ConfirmDialog
controller DeleteMemberController
controller OpenMembersController
model MemberDao
model Member
user -right-> MembersManagementView
note on link
deleteMember()
end note
user -right-> DeleteMemberDialog
note on link
setMember(member)
confirm()
cancel()
end note
MembersManagementView -down-> DeleteMemberDialog
note on link
new DeleteMemberDialog()
end note
DeleteMemberDialog -down-> ConfirmDialog
note on link
new ConfirmDialog()
end note
DeleteMemberDialog -right-> DeleteMemberController
note on link
 deleteMember(member)
end note

MembersManagementView -right-> OpenMembersController
note on link
readMembers()
end note
DeleteMemberController -right-> MemberDao
note on link
deleteMember(member)
end note

OpenMembersController -down-> MemberDao
note on link
readMembers()
end note
MemberDao *-down-> Member

@enduml
