@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view UseCasesView
view DeleteUseCaseDialog
view ConfirmDialog
controller DeleteUseCaseController
controller OpenUseCasesController
model UseCaseDao
model UseCase

user -right-> UseCasesView
note on link
deleteUseCase()
end note
user -right-> DeleteUseCaseDialog
note on link
setUseCase(selectedUseCase)
confirm()
cancel()
end note
UseCasesView -down-> DeleteUseCaseDialog
note on link
new DeleteUseCaseDialog()
end note
DeleteUseCaseDialog -down-> ConfirmDialog
note on link
new ConfirmDialog()
end note
DeleteUseCaseDialog -right-> DeleteUseCaseController
note on link
 DeleteUseCase(useCase)
end note

UseCasesView -right-> OpenUseCasesController
note on link
readUseCases()
end note
DeleteUseCaseController -right-> UseCaseDao
note on link
deleteUseCase(useCase)
end note

OpenUseCasesController -down-> UseCaseDao
note on link
readUseCases()
end note
UseCaseDao *-down-> UseCase

@enduml
