@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view IterationView
view ConfirmDialog
controller MergeActivityController
model ActivitiesDao

user -right-> IterationView
    note on link
        mergeActivity(activityId)
    end note
user -down-> ConfirmDialog
    note on link
        confirm()
        cancel()
    end note

IterationView --> ConfirmDialog
    note on link
        new ConfirmDialog()
    end note

IterationView -right-> MergeActivityController
    note on link
        merge(activityId)
    end note
MergeActivityController -down-> ActivitiesDao
    note on link
        delete(activityId)
    end note

@enduml
