@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view PlanProjectView
controller OpenPhasesController
model Project
model Phase

user -down-> PlanProjectView
note on link
openPhases()
end note
PlanProjectView -right-> OpenPhasesController
note on link
readPhases()
end note
OpenPhasesController -right-> Project
note on link
readPhases()
end note
Project *-down-> Phase

@enduml
