@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view PlanProjectView
controller OpenPhasesController
model ProjectEntity
model PhaseEntity

user -down-> PlanProjectView
note on link
openPhases()
end note
PlanProjectView -right-> OpenPhasesController
note on link
readPhases()
end note
OpenPhasesController -right-> ProjectEntity
note on link
readPhases()
end note
ProjectEntity *-down-> PhaseEntity

@enduml