@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view MembersManagementView
view UseCasesManagementView
view ProjectManagementView
controller OpenMembersController
model MembersDAO
model Member

user -down-> ProjectManagementView
note on link
openMembers()
end note

user -down-> UseCasesManagementView
note on link
openMembers()
end note

ProjectManagementView --> MembersManagementView
note on link
    openMembers()
end note

UseCasesManagementView --> MembersManagementView
note on link
    openMembers()
end note

MembersManagementView -right-> OpenMembersController
note on link
readMembers()
end note

MembersManagementView --> Member
note on link
    getName()
    getRoles()
    getEmail()
end note

OpenMembersController -right-> MembersDAO
note on link
readMembers()
end note

OpenMembersController -- "0..*" Member

MembersDAO *-down- Member

@enduml