@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

skinparam linetype polyline

actor user

view PhaseView
view PhasesView
view IterationView

controller OpenIterationsController

model Phase
model Iteration
model PhaseDAO

user -right-> PhasesView
note on link
    openPhase(phaseId)
end note

IterationView -right-> PhaseView
note on link
    openPhase(phaseId)
end note

PhasesView --> PhaseView
note on link
    openPhase(phaseId)
end note

PhaseView -right-> Phase
note on link
    getName()
    getStartDate()
    getEndDate()
    getIterations()
    getIteration().getId()
    getIteration().getStartDate()
    getIteration().getEndDate()
    getIteration().getDuration()
    getIteration().getProgress()
end note

PhaseView -right-> OpenIterationsController
note on link
    openPhase(phaseId)
end note

OpenIterationsController -- "1" Phase

OpenIterationsController -right-> PhaseDAO
note on link
    readPhase(phaseId)
end note

PhaseDAO -- Phase

Phase *-right-> "*" Iteration
note on link
    getId()
    getStartDate()
    getEndDate()
    getDuration()
    getProgress()
end note

@enduml