@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view IterationsView
view IterationView

controller OpenIterationsController
model IterationDao
model Iteration

user -right->IterationsView
    note on link
        openIteration(iterationId)
    end note
IterationsView -down-> IterationView
    note on link
        new IterationsView(iterationId)
    end note
IterationView -right-> OpenIterationsController
    note on link
        get(iterationId)
    end note
OpenIterationsController -right-> IterationDao
    note on link
        get(iterationId)
    end note

OpenIterationsController .down.> Iteration
IterationView .down.> Iteration
@enduml

