@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

skinparam linetype polyline

actor user

view IterationsView
view PhasesView

controller OpenIterationsController

model Phase
model Iteration
model PhaseDAO

user -right-> PhasesView
    note on link
        openPhase(phaseId)
    end note

PhasesView -down-> IterationsView
note on link
    new IterationsView(phaseId)
end note
IterationsView -right-> OpenIterationsController
    note on link
        getPhase(phaseId)
    end note

OpenIterationsController ..> Phase
OpenIterationsController -right-> PhaseDAO
    note on link
        getPhase(phaseId)
    end note

IterationsView ..> Iteration
PhaseDAO --> Phase
Phase o--> Iteration
@enduml
