@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view PhaseView
view OpenIterationSelectUseCasesView
view IterationView

collaboration collaboration_openPhase
controller OpenIterationsController
collaboration collaboration_ShowIteration

model IterationDAO
model Iteration
model Discipline
model Usecase

user -right-> PhaseView
    note on link
        openIteration(iterationId)
    end note

user -right-> OpenIterationSelectUseCasesView
note on link
    selectUsecase(usecaseId)
    setDesiredRealization(usecaseId, desiredRealization)
    confirmPlanIteration()
    cancel()
end note

PhaseView -right-> IterationView
    note on link
        openIteration(iterationId)
    end note

IterationView -- OpenIterationSelectUseCasesView
    note on link
        <-- new OpenIterationSelectUseCasesView(iterationId)
        --> showIteration(iterationId)
    end note


IterationView -right-> collaboration_ShowIteration
note on link
 showIteration(iterationId)
end note

OpenIterationSelectUseCasesView --> OpenIterationsController
note on link
    confirmPlanIteration(selectedUsecases)
end note

OpenIterationSelectUseCasesView --> Usecase
note on link
    setDesiredRealization(desiredRealization)
end note

OpenIterationSelectUseCasesView --> PhaseView
note on link
    cancel()
end note

IterationView -right-> OpenIterationsController
note on link
    openIteration(iterationId)
end note

PhaseView -up-> collaboration_openPhase
note on link
    openPhase(phaseId)
end note

OpenIterationsController -- "*" Usecase

OpenIterationsController -right-> IterationDAO
note on link
    readIteration(iterationId)
    updateIteration(iteration)
end note

OpenIterationsController -right-> Iteration
note on link
    initNotAsignedCosts(selectedUsecases)
end note

OpenIterationsController -- Discipline

Iteration *-- "6" Discipline
note on link
    initNotAsignedCost(usecases)
end note

IterationDAO -- Iteration

@enduml

