@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view UseCasesManagementView
controller OpenUseCasesController
model UseCaseDao
model UseCase

user -down-> UseCasesManagementView
note on link
openUseCases()
end note

UseCasesManagementView -right-> OpenUseCasesController
note on link
readUseCases()
end note
OpenUseCasesController -right-> UseCaseDao
note on link
readUseCases()
end note
UseCaseDao *-down-> UseCase

@enduml
