@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view ProjectManagementView
view PhaseView

controller ProjectManagementController
controller OpenIterationsController
model IterationDao
model Iteration

user -down-> PhaseView
note on link
setIteration(iteration)
end note
user -right->ProjectManagementView
note on link
openIteration()
end note
ProjectManagementView -right-> ProjectManagementController
note on link
getIterations()
end note
ProjectManagementController -down-> IterationDao
note on link
getIterations()
end note
IterationDao *-down-> Iteration
PhaseView -right->OpenIterationsController
note on link
getIteration(iteration)
end note
ProjectManagementView -down-> PhaseView
OpenIterationsController -right-> IterationDao
note on link
getIteration(iteration)
end note

Iteration -left-> OpenIterationsController
note on link
<b>requested Iteration</b>
end note
@enduml

