@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view UseCasesManagementView

controller PrioritizeUseCaseController

model UseCaseDao
model UseCase

user -down-> UseCasesManagementView
    note on link
        prioritize(useCaseId, priorityValue)
    end note
UseCasesManagementView -right-> PrioritizeUseCaseController
    note on link
        patchUseCase(useCase)
    end note
PrioritizeUseCaseController -right-> UseCaseDao
    note on link
        patch(useCase)
    end note

UseCasesManagementView o.down.> UseCase
PrioritizeUseCaseController o.down.> UseCase
UseCaseDao o.down.> UseCase

@enduml
