@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view UseCasesManagementView
controller PrioritizeUseCaseController
controller OpenUseCasesController
model UseCaseDAO
model UseCase

user -right-> UseCasesManagementView
note on link
prioritizeUseCases()
setPrioritization(useCase, value)
confirm()
cancel()
end note

UseCasesManagementView  -right-> UseCase
note on link
    getName()
    getPrioritization()
    setPrioritization(value)
end note

UseCasesManagementView -right-> PrioritizeUseCaseController
note on link
prioritizeUseCases(usecaseList)
end note

PrioritizeUseCaseController -right-> UseCaseDAO
note on link
updateUseCase(usecase)
end note

UseCasesManagementView -right-> OpenUseCasesController
note on link
readUseCasesSortedByPriority(desc)
end note

PrioritizeUseCaseController -down- "*" UseCase

OpenUseCasesController -down-> UseCaseDAO
note on link
readUseCases()
end note

UseCaseDAO *-down- UseCase
@enduml