@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view UseCasesManagementView
view PrioritizeUseCaseDialog
view ConfirmDialog
controller PrioritizeUseCaseController
controller OpenUseCasesController
model UseCaseEntities
model UseCaseEntity

user -right-> UseCasesManagementView
note on link
prioritizeUseCase()
end note
user -right-> PrioritizeUseCaseDialog
note on link
setPositions(useCasesValues[])
confirm()
cancel()
end note
UseCasesManagementView -down-> PrioritizeUseCaseDialog
note on link
new PrioritizeUseCaseDialog()
end note
PrioritizeUseCaseDialog -down-> ConfirmDialog
note on link
new ConfirmDialog()
end note
PrioritizeUseCaseDialog -right-> PrioritizeUseCaseController
note on link
 PrioritizeUseCase(useCasesValues[])
end note

UseCasesManagementView -right-> OpenUseCasesController
note on link
readUseCases()
end note
PrioritizeUseCaseController -right-> UseCaseEntities
note on link
updateUseCase(useCase)
end note
PrioritizeUseCaseController -down-> UseCaseEntity
note on link
<b>foreach(useCasesValues as useCase):</b>
getUseCase(useCase)
end note
OpenUseCasesController -down-> UseCaseEntities
note on link
readUseCases()
end note
UseCaseEntities *-down-> UseCaseEntity

@enduml