@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user
view IterationView
view RestimateActivityView
view ConfirmDialog
controller OpenIterationController
controller RestimateActivityController
model Iteration
model Activity
model ActivitiesDAO

user -right-> IterationView

note on link
restimateActivity()
end note
user -down-> RestimateActivityView
note on link
getActivity()
getRestimateCost()
confirm()
cancel()
end note

RestimateActivityView -left-> ConfirmDialog

IterationView -down-> RestimateActivityView
note on link
new RestimateActivityView()
end note

IterationView -down--> OpenIterationController
note on link
    getIteration(currentIteration)
end note

RestimateActivityView -down-> RestimateActivityController
note on link 
    restimateActivity(actividad, restimateCost)
    updateNotAsignerCost()
end note

RestimateActivityController -down-> ActivitiesDAO
note on link
updateActivity(activity)
end note

OpenIterationController -down--> Iteration
note on link
    getIteration(currentIteration)
end note

Iteration *-down- Activity
ActivitiesDAO *-right- Activity


@enduml