@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view IterationView

controller RestimateActivityController

model Activity
model ActivitiesDAO

user -right-> IterationView
    note on link
        reestimateActivity(activityId, duration)
    end note

IterationView -right-> RestimateActivityController
    note on link
        patch(activity)
    end note

RestimateActivityController -down-> ActivitiesDAO
    note on link
        patch(activity)
    end note

IterationView .down.> Activity
RestimateActivityController .down.> Activity
ActivitiesDAO .left.> Activity

@enduml
