@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view IterationView

controller RestimateActivityController

model Activity
model ActivitiesDao

user -down-> IterationView
    note on link
        reestimateActivity(activityId, duration)
    end note

IterationView -right-> RestimateActivityController
    note on link
        reestimateActivity(activityId, duration)
    end note

RestimateActivityController -down-> ActivitiesDao
    note on link
        patch(activity)
    end note

RestimateActivityController .down.> Activity
ActivitiesDao .left.> Activity

@enduml
