@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

skinparam linetype polyline

view IterationView

controller ShowIterationController

model IterationDAO
model MemberDAO
model Iteration
model Discipline
model Usecase
model Activity
model Member

IterationView -right-> ShowIterationController
note on link
    readIteration(iterationId)
    readMembers()
end note

IterationView -right-> Iteration
note on link
    getId()
    getTimeInterval()
    getActivity().getTimeInterval()
    getActivity().getMember()
    getActivity().getType()
    getUsecase().getDescription()
    getDiscipline().getName()
    getDiscipline().getNotAssignedCost()
end note

IterationView -right-> Member
    note on link
        getName()
    end note

ShowIterationController -down-> MemberDAO
note on link
    readMembers()
end note

ShowIterationController -down-> IterationDAO
note on link
    readIteration(iterationId)
end note

IterationDAO --down- Iteration
MemberDAO -down- Member

ShowIterationController -down- "1" Iteration
ShowIterationController -down- "*" Member

Iteration *-right-> "6" Discipline
note on link
    getName()
    getNotAssignedCost()
    getActivities()
end note

Discipline *--> "*" Activity
note on link
    getMember()
    getUsecase()
    getStart()
    getEnd()
end note

Activity --> Member
note on link
    getName()
end note

Activity -right-> Usecase
note on link
    getDescription()
end note

@enduml

