@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

left to right direction

actor user
view InitProjectView
controller StartSystemController
model Project

user --> InitProjectView
note on link
openApp()
end note

InitProjectView --> StartSystemController
note on link
getProject()
end note

InitProjectView --> Project
note on link
    getStartDate()
    getEndDate()
    getDuration()
    getProgress()
    getIterationDuration()
end note

StartSystemController --> Project
note on link
getProject()
end note

@enduml
