d@startuml

!include configuration/skinParams.puml
!include configuration/definitions.puml

actor user

view UseCasesView
view UpdateUseCaseDialog

controller UpdateUseCaseController

model UseCaseDao
model UseCase

user -right-> UseCasesView
    note on link
        updateUseCase(useCaseId)
    end note
user -right-> UpdateUseCaseDialog
    note on link
        setName(name)
        setRole(role)
        confirm()
        cancel()
    end note
UseCasesView -down-> UpdateUseCaseDialog
    note on link
        new UseCaseDialog(useCaseId)
    end note
UpdateUseCaseDialog -right-> UpdateUseCaseController
    note on link
        updateUseCase(useCase)
    end note
UpdateUseCaseDialog -right-> UseCase
UpdateUseCaseController -right-> UseCaseDao
    note on link
        update(useCase)
    end note

UpdateUseCaseController .down.> UseCase
UseCaseDao ..> UseCase

@enduml
