@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}
	state INICIAL1 as ":USE_CASES_MANAGEMENT"
	state INICIAL2 as ":PROJECT_MANAGEMENT"
	state INICIAL3 as ":MEMBERS_MANAGEMENT"
	state FINAL as ":ITERATION_MANAGEMENT"
    
    INICIAL1 --> OpenIteration  

    INICIAL2 --> OpenIteration
        note on link
        User requests to Open Iterations
    end note
    
    INICIAL3 --> OpenIteration
    
	state OpenIteration {
    
	    state 1  <<choice>>
	    state 2 as "CONFIGURING_CURRENT_ITERATION" #Cyan
	    state 3 <<choice>>
	    
	
	    [*] --> 1

      	1 -> [*]
	    note on link #GreenYellow
	        [There is current iteration]
	    end note

	    1 --> 2
	    note on link
	        [empty current iteration]
	    end note

	    2 --> 3
	    note on link
	        <b>System shows</b>
	        * Use cases ordered by prioritization
	        <b>System allows</b>
	        * Introduce use case for the current iteration
	        * Introduce this use cases desired realization:
	           REQUIREMENTS 
	           | ANALYSIS 
	           | DESIGN 
	           | IMPLEMENTATION
	    end note
	    3 --> 2
	       note on link
	        <b>System shows</b>
	        * More than one usecases should be introduced
	        * Some use case has not desired realization
	    end note
	    3 --> [*]
	    note on link
	        <b>User request</b>
	        * Confirm open current iteration
	           <b>AND</b>
	        * [usecases introduced >= 1 AND All use cases introduced have desired realization]  
	    end note
	}

    OpenIteration --> FINAL
    note on link #GreenYellow
    <b>System shows</b>
    * For each member
    ** AssignedActivities in his datetime until end of current iteration
    * For each discipline (requirements, analysis, design, implementation)
    ** NotAssignedCost
    ** NotAssignedActivities (with activity type)
    <b>System allows</b>
    * Split activity
    * Assign activity
    * Re-estimate activity
    * Merge activity
    * Open members
    * Close system
   	end note

	
@enduml
