@startuml
skinparam NoteBackgroundColor #whiteSmoke
state init as "MEMBER_MANAGEMENT"
state end as "MEMBER_MANAGEMENT"
init ---> CreateMemberUseCase
note on link
    User request create new Member
    <b>System show</b>
    * All members
    <b>System allow</b>
    *Create member
    *Delete member
    *Update member
end note
state CreateMemberUseCase {
    state initial as " "#LawnGreen
    state 2 <<choice>> #LawnGreen
    state 3 as " "#LawnGreen
    state 4 as " "
    state 5 as " "#LawnGreen
    [*]-->initial
    note on link
    <b>System allow</b>
    * introduce member name
    * introduce email
    * Cancel
     <b>System require</b>
    * member email as unique   
    end note
    initial-->4
    note on link
    User cancel
    end note
    4->5
    5->[*]
    note on link    
    <b>System show</b>
    * All members    
end note   
    2-left->initial
    note on link
    Validation error
    end note
    initial-->2           
    2-->3
    note on link
    Member created
    end note
    3-->5    
    CreateMemberUseCase --> end    
     
}
@enduml