@startmindmap
* Start System
** Plan Project
** PROJECT MANAGEMENT
*** Open Phases 
*** Open Iterations
**** ITERATION MANAGEMENT
***** USE CASES MANAGEMENT 
****** Proritize Use Cases
****** Create Use Case
****** Update Use Case
****** Delete Use Case
@endmindmap