@startuml

node client
node server

'together con todas las del servidor
' '' con las del cliente

node webAppContainer <<docker-container>> as "WebApp"
node webServerContainer <<docker-container>>  as "ApiRest Server"
node databaseContainer <<docker-container>>  as "BBDD"

node webClient
client <|-- webClient

component webApp as "rup-project-webApp" <<angular>>
component angular as "angular" <<angular>>
component webServerApp as "rup-project.jar" <<java>>
component pumlGenerator as "puml-generator.jar" <<java>>
database rupProjectsDataBase as "rupProjectsDataBase" <<MariaDB>>

client .[hidden]right. server
webServerApp .[hidden]left. webApp

server --> webAppContainer
server --> webServerContainer
server --> databaseContainer
webAppContainer *--> webApp
webAppContainer *--> angular
webApp .down.>angular
webServerContainer --> webServerApp
webServerContainer --> pumlGenerator
webServerApp -left-> pumlGenerator
databaseContainer --> rupProjectsDataBase
webServerApp -right-> rupProjectsDataBase

@enduml
