@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user
view MembersManagementView
view CreateMemberDialog
controller CreateMemberController
model MembersDao
model Member

user -right-> MembersManagementView
note on link
createMember()
end note
user -right-> CreateMemberDialog
note on link
setName(name)
setRoles(roles)
confirm()
cancel()
end note
MembersManagementView -down-> CreateMemberDialog
note on link
    new MemberDialog()
end note
CreateMemberDialog -right-> CreateMemberController
note on link
    createMember(member)
end note
CreateMemberDialog -right-> Member
CreateMemberController -right-> MembersDao
note on link
    create(member)
end note

CreateMemberController .down.> Member
MembersDao ..> Member
@enduml
