@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user

view MembersView
view UpdateMemberDialog

controller UpdateMemberController

model MembersDao
model Member

user -right-> MembersView
    note on link
        updateMember(memberId)
    end note

user -down-> UpdateMemberDialog
    note on link
        setName(name)
        setRoles(roles)
        confirm()
        cancel()
    end note

MembersView -down-> UpdateMemberDialog
    note on link
        new UpdateMemberDialog(memberId)
    end note

UpdateMemberDialog -down-> UpdateMemberController
    note on link
            updateMember(member)
    end note
UpdateMemberController -down-> MembersDao
    note on link
        updateMember(member)
    end note


UpdateMemberDialog .right.> Member
UpdateMemberController .right.> Member

MembersDao .right.> Member


@enduml
