@startuml

!include skinParams.puml

 skinparam linetype polyline


    'analysis
    boundary XView #9FB7E5
    control XController #C4E4AB
    entity XEntity #F8D987
    entity XEntities #F8D987

    'Design
    boundary XStyle as "XStyle - CSS"
    boundary XTemplate as "XTemplate - HTML"
    boundary XComponent as "XComponent - TypeScript"
    control XResource as "XResource - java"
    entity HTTPService
    control XControllerDesign as "XController - java"
    control XService as "XService - TypeScript"
    entity XRepository as "XRepository - java"
    entity XDto as "XModel - java"
    entity XDtoJava as "XDto - java"
    entity XEntityDesign as "XEntity - java"


    XView -right-> XController
    XView --> XEntity
    XController -right-> XEntity
    XController -right-> XEntities

    XTemplate ...[#Gray]up.> XView : <<trace>>
    XStyle ...[#Gray]up.> XView : <<trace>>
    XComponent ...[#Gray]up.> XView : <<trace>>
    XService ...[#Gray]up.> XController : <<trace>>
    XDto ...[#Gray]up.> XEntity : <<trace>>
    XResource ...[#Gray]up.> XController : <<trace>>
    XControllerDesign ...[#Gray]up.> XController : <<trace>>
    XDtoJava ...[#Gray]up.> XEntity : <<trace>>
    XEntityDesign ...[#Gray]up.> XEntity : <<trace>>
    XRepository ...[#Gray]up.> XEntities : <<trace>>

    XComponent -left-> XTemplate
    XTemplate -left-> XStyle
    XComponent --> XDto
    XComponent -right-> XService
    XDto .[#Gray]right.> XDtoJava : <<trace>>

    XService .[#Gray]right.> XResource : <<trace>>
    XResource -right-> XControllerDesign
    XService --down-> XDto
    XService o-- HTTPService
    XResource --down-> XDtoJava
    XControllerDesign --down-> XEntityDesign
    XControllerDesign -right-> XRepository
    XControllerDesign -right-> XDtoJava
    XDtoJava -right-> XEntityDesign
    XRepository -right-> XEntityDesign





@enduml