@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user

view IterationView
view SplitActivityView

controller SplitActivityController

model Activity
model UseCase
model ActivitiesDao
model UseCaseDao

user -right-> IterationView
    note on link
        splitActivity(disciplineId)
    end note
user --> SplitActivityView
    note on link
        setUseCaseId()
        setDescription()
        setCost()
        confirm()
        cancel()
    end note
IterationView -down-> SplitActivityView
    note on link
        new SplitActivityView(disciplineId)
    end note
SplitActivityView -right-> SplitActivityController
    note on link
        splitActivity(activity)
        getAllUseCases()
    end note
SplitActivityController -down-> ActivitiesDao
    note on link
        createActivity(activity)
    end note
SplitActivityController -down-> UseCaseDao
    note on link
        getAll()
    end note

SplitActivityView ..> Activity
SplitActivityView o..> UseCase
SplitActivityController ..> Activity

UseCaseDao ..> UseCase
ActivitiesDao ..> Activity

@enduml
