@startuml
left to right direction

:Manager: --> (Create UseOfCase)
:Manager: --> (Show UseOfCase)
:Manager: --> (Update UseOfCase)
:Manager: --> (Delete UseOfCase)

:Manager: --> (Visualize UseOfCases)
@enduml
