@startuml
left to right direction

actor "Manager" as manager

package project {
:manager: --> (Open project)
:manager: --> (Plan project)
:manager: --> (Delete project)
}

package UseCases {
:manager: --> (Open use of cases)
:manager: --> (Create use of case)
:manager: --> (Remove use of case)
:manager: --> (Edit use of case)
:manager: --> (Prioritize use of case)
}

package Members {
:manager: --> (Create member)
:manager: --> (Edit member)
:manager: --> (Show members)
}

package Activities {
:manager: --> (Assign activity)
:manager: --> (Re-estimate activity)
:manager: --> (Split activity)
:manager: --> (Close activity)
:manager: --> (Join activity)
}

@enduml
