@startuml

[*] --> OPENED_PROJECT : startSystem

OPENED_PROJECT --> [*] : closeSystem
USE_CASES_MANAGEMENT --> [*] : closeSystem
MEMBER_MANAGEMENT --> [*] : closeSystem
OPENED_ITERATION --> [*] : closeSystem

OPENED_PROJECT --> OPENED_PROJECT : Plan project \n Refresh \n change zoom
OPENED_PROJECT --> USE_CASES_MANAGEMENT : Open use cases
OPENED_PROJECT --> MEMBER_MANAGEMENT : Open members
OPENED_PROJECT --> OPENED_ITERATION : Open iteration

USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Create use case \n Edit use case \n Delete use case
USE_CASES_MANAGEMENT --> OPENED_PROJECT : Open project
MEMBER_MANAGEMENT --> MEMBER_MANAGEMENT : Create member \n Edit member \n Remove member \n
MEMBER_MANAGEMENT --> OPENED_PROJECT : Open project
OPENED_ITERATION --> OPENED_ITERATION : Assign activity \n Re-estimate activity \n Split activity \n Join activity \n Close Activity
OPENED_ITERATION --> OPENED_PROJECT : Open project
@enduml