@startuml InitProjectNavigation
!include ../procedures/SaltProcedure.puml
!include ../procedures/project/ProjectManagement.puml
!include ../procedures/project/PlanProject.puml
!include ../procedures/project/InitProject.puml


INIT_PROJECT -down-> SALT(initProject) #LawnGreen
initProject -right-> SALT(planProject)
    note on link
    plan project
    end note
initProject -down-> SALT(projectManagement)
note on link
Open
end note
planProject -left-> SALT(initProject)
    note on link
    cancel
    end note

planProject -down-> SALT(projectManagement) #LawnGreen


projectManagement --> PROJECT_MANAGEMENT
PROJECT_MANAGEMENT --> projectManagement

@enduml