@startuml

state 1 <<choice>>
state 2 <<choice>>
state 3 <<choice>>
state 4 <<choice>>
state 5 <<choice>>
state 6 <<choice>>

[*] --> 1 : Manager request to open project
1 --> 2 : System allows to provide the dates to plan the project
2 --> 3 : Manager provides the project information
3 -> 4 : System allows to plan the project
4 -> 5 : Manager request to plan the project
5 ---> 6 : System shows the project planning and allow to make modifications
6 -> 3 : Manager provide new project information

6 --> [*]
@enduml
