@startuml

top to bottom direction
skinparam Linetype ortho

View *-- DeploymentView

DeploymentView *-- "1" index
index .[#000000].> Deployment
index .[#000000].> Installation
index .[#000000].> Distribution
DeploymentView *-- "1" Deployment
DeploymentView *-- "1" Installation
DeploymentView *-- "1" Distribution
Deployment .[#000000].> Diagrams.DeployDiagram
Installation .[#000000].> Diagrams.DeployDiagram
Distribution .[#000000].> Diagrams.DeployDiagram
index .[#000000].> Diagrams.ContentDiagram


@enduml