@startuml

top to bottom direction
skinparam Linetype ortho

namespace Analysis{
    Class AnalysisArchitecture
    Class UseCaseAnalysis
    Class UseCase
    Class ClassAnalysis
    Class PackageAnalysis
}

namespace Design{
    Class System
    Class Subsystem
    Class UseCaseAnalysis
    Class ClassDesign
    Class DesignArchitecture

}

View *-- DesignView
DesignView *-left- "1" index
DesignView *-- "1" Analysis.AnalysisArchitecture
DesignView *-- "1" Analysis.UseCaseAnalysis
DesignView *-- "1..*" Analysis.PackageAnalysis
DesignView *-- "1..*" Analysis.ClassAnalysis
DesignView *-- "1" Design.DesignArchitecture
DesignView *-- "1..*" Design.ClassDesign
DesignView *-- "1" Design.UseCaseAnalysis
DesignView *-- "1..*" Design.System

Analysis.AnalysisArchitecture .[#000000].> Diagram.PackageDiagram
Analysis.UseCaseAnalysis .[#000000].> Diagram.ClassDiagram
Analysis.UseCaseAnalysis .[#000000].> Diagram.CommunicationDiagram
Analysis.ClassAnalysis .[#000000].> Diagram.ClassDiagram
Analysis.PackageAnalysis .[#000000].> Diagram.ClassDiagram
Analysis.UseCaseAnalysis *-- Analysis.UseCase

Design.ClassDesign --> Analysis.ClassAnalysis : depends on
Design.DesignArchitecture "depends on" --> Analysis.AnalysisArchitecture
Design.Subsystem .[#000000].> Diagram.PackageDiagram
Design.UseCaseAnalysis .[#000000].> Diagram.ClassDiagram
Design.System *-- Design.Subsystem
index .[#000000].> Diagram.ContentDiagram
@enduml