@startuml

top to bottom direction
skinparam Linetype ortho

View *-- ProcessView
ProcessView *-- "1" index
ProcessView *-- "1" Process
index .[#000000].> Process
Process .[#000000].> Diagram.SequenceDiagram
index .[#000000].> Diagram.ContentDiagram

@enduml