@startuml

state Initial as "INITIAL"
state ProjectOpened as " "
state UseCasesOpened as " "
state MembersOpened as " "
state ActivitiesOpened as " "

[*] --> Initial : StartSystem

Initial --> ProjectOpened : OpenProject
Initial --> UseCasesOpened : OpenUseCases
Initial --> MembersOpened : OpenMembers
Initial --> ActivitiesOpened : OpenActivities


ProjectOpened -down-> ProjectOpened : PlanProject
ProjectOpened -down-> Initial : DeleteProject

UseCasesOpened -down-> UseCasesOpened : CreateUseCase \n EditUseCase \n DeleteUseCase \n PrioritizeUseCase
MembersOpened -down-> MembersOpened : ShowMembers \n CreateMember \n EditMember \n DeleteMember
ActivitiesOpened -down-> ActivitiesOpened : AssignActivity \n ReestimateActivity \n SplitActivity \n JoinActivity \n CloseActivity

@enduml
