@startuml
left to right direction

actor "Manager" as manager

package General {
:manager: -down-> (startSystem)
:manager: -down-> (closeSystem)
:manager: -down-> (OpenProject)
:manager: -down-> (openPhases)
:manager: -down-> (openIterations)
:manager: -down-> (PlanProject)
:manager: -down-> (CloseIteration)
}

package Members {
:manager: -down-> (OpenMembers)
:manager: -down-> (CreateMember)
:manager: -down-> (UpdateMember)
:manager: -down-> (DeleteMember)
}

package UseCases {
:manager: -left-> (OpenUseCases)
:manager: -left-> (CreateUseCase)
:manager: -left-> (DeleteUseCase)
:manager: -left-> (UpdateUseCase)
:manager: -left-> (PrioritizeUseCases)
}

package Disciplines {
:manager: -left-> (OpenIteration)
:manager: -left-> (AssignActivity)
:manager: -left-> (Re-estimateActivity)
:manager: -left-> (SplitActivity)
:manager: -left-> (CloseActivity)
:manager: -left-> ("fundirActivity")
}



@enduml
