@startuml



[*] --> INIT_PROJECT
 note on link
    start System
 end note
INIT_PROJECT -down-> OPENED_PROJECT
    note on link
        Plan project
        Open project
    end note

INIT_PROJECT            -down-> [*] : closeSystem
OPENED_PROJECT          -down-> [*] : closeSystem
USE_CASES_MANAGEMENT    -down-> [*] : closeSystem
MEMBER_MANAGEMENT       -down-> [*] : closeSystem
OPENED_ITERATION      -down-> [*] : closeSystem

OPENED_PROJECT --> OPENED_PROJECT
    note on link
        Open phases
        Open Iterations
    end note
OPENED_PROJECT --> USE_CASES_MANAGEMENT : Open use cases
OPENED_PROJECT --> MEMBER_MANAGEMENT    : Open members
OPENED_PROJECT --> OPENED_ITERATION
    note on link
        Open iteration (si vacia,
        selecciona casos de uso
        y hasta donde quiere llegar del ucase generar pastillas
        actividades no ligadas a caso de uso 1h, las de caso de
         uso si se quiere \n llegar a ese nv de disciplina)
    end note
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT
    note on link
        Prioritize Use cases
        Create use case
        Update use case
        Delete use case
    end note
USE_CASES_MANAGEMENT --> OPENED_PROJECT         : Open project
USE_CASES_MANAGEMENT --> MEMBER_MANAGEMENT      : Open members
USE_CASES_MANAGEMENT --> OPENED_ITERATION     : Open iteration

MEMBER_MANAGEMENT --> MEMBER_MANAGEMENT
    note on link
        Create member
        Update member
        Remove member
    end note
MEMBER_MANAGEMENT --> OPENED_PROJECT        : Open project
MEMBER_MANAGEMENT --> USE_CASES_MANAGEMENT  : Open use cases
MEMBER_MANAGEMENT --> OPENED_ITERATION    : Open iteration

OPENED_ITERATION --> OPENED_ITERATION
    note on link
        Assign activity (chequear si la iteracion ya esta cerrada)
        Re-estimate activity
        Split activity
        Merge activity
        Close Activity
        Close Iteration
    end note
OPENED_ITERATION --> OPENED_PROJECT : Open project
OPENED_ITERATION --> MEMBER_MANAGEMENT : Open members
OPENED_ITERATION --> USE_CASES_MANAGEMENT : Open use cases
@enduml