@startuml
left to right direction

:Manager: --> (create use case)
:Manager: --> (list use cases)
:Manager: --> (edit use case)
:Manager: --> (delete use case)
:Manager: --> (prioritize use case)

@enduml