@startuml
left to right direction
(plan project) as (planProject)

:Manager: --> (planProject)
:Manager: --> (show project)
:Manager: --> (plan phase)
:Manager: --> (plan Iteration)
:Manager: --> (move activity)
:Manager: --> (re-size activity)
:Manager: --> (split activity)


@enduml