@startuml
	class RestimateActivityController {
	+reestimateActivity(activityId, duration)
	}

	IterationView --> RestimateActivityController
	RestimateActivityController ..> Activity
	RestimateActivityController --> ActivitiesDao
@enduml
