@startuml
skinparam NoteBackgroundColor #whiteSmoke


'Initial/end states
state init as "USE_CASE_MANAGEMENT"
state end as "USE_CASE_MANAGEMENT"

init ---> CreateUseCase
CreateUseCase ---> end
note on link
<b>System allows</b>
* create member
* create member
* delete member
* open project
* open iteration
* open use cases
end note

'Use case specfication
state CreateUseCase {
    state createOrdered as " "
    state requiredUseCaseToCreate as " "
    state selectedUseCase as " "
    state editUseCase as " "
    state editedUseCase  <<choice>>
    state requireToConfirm  as " "
    state savedUseCase as " "
    state errorValidation as " "
    state toConfirm as " "
    state systemSave as " "

    'Main path
    [*] --> createOrdered
    note on link
        <b>User request</b>
        * to create a use case
    end note
    createOrdered --> requiredUseCaseToCreate
    note on link
        <b>System require</b>
        * The use case to be created
    end note
    requiredUseCaseToCreate --> selectedUseCase
    note on link
        <b>User provide</b>
        * The use case to create
    end note
    selectedUseCase --> editUseCase
    note on link
        <b>System require</b>
        * use case name
        <b>System allows</b>
        * Cancel
    end note
    editUseCase --> editedUseCase
    note on link
        <b>User provide</b>
        * use case name
    end note
    editedUseCase --> toConfirm
    toConfirm --> requireToConfirm
            note on link
            <b>System allow</b>
             * confirm
             * cancel
            end note
    requireToConfirm --> systemSave
        note on link
        <b>User</b> confirm
        end note
    systemSave --> savedUseCase
        note on link
            <b>System shows</b>
            * The use case has been created
        end note
    savedUseCase --> [*]
           note on link
           <b>System shows</b>
           * the use case list
           end note

    'variation path
    editedUseCase --> errorValidation
        note on link
        [ length(useCaseName) out of 5,25 ]
        end note

    errorValidation --> selectedUseCase
            note on link
            <b>System shows</b>
            * The name length is not correct
            end note

    'variation path
    requireToConfirm --> savedUseCase
    note on link
          <b>User</b> cancel
    end note

    'variation path
    editUseCase --> savedUseCase
    note on link
          <b>User</b> cancel
    end note

}

@enduml
