@startuml
skinparam NoteBackgroundColor #whiteSmoke

state init as "USE_CASE_MANAGEMENT"
state end as "USE_CASE_MANAGEMENT"

init ---> CreateUseCase
CreateUseCase ---> end
note on link
<b>System allows</b>
* create member
* update member
* delete member
* open project
* open iteration
* open use cases
end note

state CreateUseCase {
    state orderCreateUseCase as " "
    state createOrdered as " "
    state opened as " "
    state filled as " "
    state valid as " "
    state saveOrdered as " "
    state cancelled as " "

    'Main path
    [*] --> createOrdered
    note on link
        User orders to create a new use case
    end note
    createOrdered --> opened
    note on link
        <b>System allows</b>
        * fill the use case data
        ** Name
        * cancel
    end note
    opened --> filled
    note on link
        User provide:
        * Name length between [5:30] characters
    end note
    filled --> valid
    note on link
        <b>System allows</b>
        * save the new use case data
    end note
    valid --> saveOrdered
    note on link
        User order to save the new user case data
    end note
    saveOrdered --> [*]
    note on link
        <b>System shows</b>
        * the use case is already saved
        * use cases list
    end note

    'Varation path
    opened --> opened
    note on link
        User provide:
         * empty name
         * used name
         * length out of [5:30] characters
    end note

    'Variation path
    opened --> cancelled
    note on link
        User order cancel
    end note
    cancelled --> [*]
}

@enduml
