@startuml
skinparam NoteBackgroundColor #whiteSmoke

state initial as " "
state selected as " "
state canDelete as " "
state deleteOrdered as " "
state confirmationRequired <<choice>>
state deleteConfirmed as " "

'Main path
[*] --> initial
note on link
    System allow to select a use case
end note
initial --> selected
note on link
    User select a use case
end note
selected --> canDelete
note on link
    System allows delete
    the selected use case
end note
canDelete --> deleteOrdered
note on link
    User order delete the use case
end note
deleteOrdered --> confirmationRequired
note on link
    System ask for confirmation
end note
confirmationRequired --> deleteConfirmed
note on link
    User confirm
end note
deleteConfirmed --> [*]
note on link
    System delete the use case
end note

'Variation path
confirmationRequired --> canDelete
note on link
    User cancel
end note

@enduml
