@startuml
skinparam NoteBackgroundColor #whiteSmoke

state init as "USE_CASE_MANAGEMENT"
state end as "USE_CASE_MANAGEMENT"

init ---> DeleteUseCase
DeleteUseCase ---> end

state DeleteUseCase {
    state initial as " "
    state deleteOrdered as " "
    state confirmationRequired <<choice>>
    state deleteConfirmed as " "
    state askedForWhichOneDelete as " "
    state showList as " "

    'Main path
    [*] --> initial
    note on link
        User order to delete a use case
    end note
    initial --> askedForWhichOneDelete
    note on link
        System show all use cases
        and ask which one wants to delete
    end note
    askedForWhichOneDelete --> deleteOrdered
    note on link
        User indicate a use case to delete
    end note
    deleteOrdered --> confirmationRequired
    note on link
        System ask for confirmation
    end note
    confirmationRequired --> deleteConfirmed
    note on link
        User confirm
    end note
    deleteConfirmed --> showList
    note on link
        System delete the use case
    end note
    showList --> [*]
    note on link
        System shows the use cases list
    end note

    'Variation path
    confirmationRequired --> showList
    note on link
        User cancel
    end note
}

@enduml
