@startuml
skinparam NoteBackgroundColor #whiteSmoke

state init as "USE_CASE_MANAGEMENT"
state end as "USE_CASE_MANAGEMENT"

init ---> DeleteUseCase
DeleteUseCase ---> end
note on link
<b>System allows</b>
* create member
* update member
* delete member
* open project
* open iteration
* open use cases
end note

state DeleteUseCase {
    state initial as " "
    state deleteOrdered as " "
    state confirmationRequired <<choice>>
    state deleteConfirmed as " "
    state askedForWhichOneDelete as " "
    state showList as " "

    'Main path
    [*] --> initial
    note on link
        User order to delete a use case
    end note
    initial --> askedForWhichOneDelete
    note on link
    <b>System shows</b>
    * all use cases
    <b>System allows</b>
    * introduce a use case to delete
    * cancel operation
    end note
    askedForWhichOneDelete --> deleteOrdered
    note on link
        User introduce a use case to delete
    end note
    deleteOrdered --> confirmationRequired
    note on link
    <b>System allows</b>
    * confirm
    * cancel
    end note
    confirmationRequired --> deleteConfirmed
    note on link
        User orders confirm
    end note
    deleteConfirmed --> showList
    note on link
    <b>System shows</b>
    * the use case has been deleted
    end note
    showList --> [*]
    note on link
    <b>System shows</b>
    * use case list
    end note

    'Variation path
    confirmationRequired --> showList
    note on link
        User cancel
    end note
}

@enduml
