@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user
view UseCasesManagementView
view CreateUseCaseDialog
controller CreateUseCaseController
model UseCaseDao
model UseCase

user -right-> UseCasesManagementView
    note on link
        createUseCase()
    end note
user -right-> CreateUseCaseDialog
    note on link
        setName(name)
        setDescription(description)
        confirm()
        cancel()
    end note
UseCasesManagementView -down-> CreateUseCaseDialog
    note on link
    new UseCaseDialog()
    end note
CreateUseCaseDialog -right-> CreateUseCaseController
    note on link
     createUseCase(useCase)
    end note
CreateUseCaseDialog -right-> UseCase
CreateUseCaseController -right-> UseCaseDao
    note on link
    create(useCase)
    end note
CreateUseCaseController .down.> UseCase
UseCaseDao .down.> UseCase

@enduml
