@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user

view MenuView
view UseCasesManagementView

controller OpenUseCasesController

model UseCaseDao
model UseCase

user -right-> MenuView
    note on link
        openUseCases()
    end note
MenuView -down-> UseCasesManagementView
    note on link
        new UseCasesManagementView()
    end note
UseCasesManagementView -right-> OpenUseCasesController
    note on link
        getAllUseCases()
    end note
OpenUseCasesController -right-> UseCaseDao
    note on link
        getAllUseCases()
    end note

UseCasesManagementView o--> UseCase
OpenUseCasesController o..> UseCase
UseCaseDao ..> UseCase

@enduml
