@startuml

  set namespaceSeparator .
  
namespace Time {
  Abstract Class Activity

  namespace Activities {

    Class EncontrarActoresyCasosdeUso extends Time.Activity
    Class PriorizarCasosdeUso extends Time.Activity
    Class DetallarCasodeUso extends Time.Activity
    Class EstructurarCasosdeUso extends Time.Activity
    Class PrototiparInterfazdeUsuario extends Time.Activity
  }
}

  Disciplines.Requirements <-left- Time.Activities.EncontrarActoresyCasosdeUso
  Disciplines.Requirements <-- Time.Activities.PriorizarCasosdeUso
  Disciplines.Requirements <-- Time.Activities.DetallarCasodeUso
  Disciplines.Requirements <-- Time.Activities.EstructurarCasosdeUso
  Disciplines.Requirements <-- Time.Activities.PrototiparInterfazdeUsuario

  Time.Activities.PriorizarCasosdeUso "depends" -up-> Time.Activities.EncontrarActoresyCasosdeUso 
  Time.Activities.DetallarCasodeUso -up-> "depends" Time.Activities.PriorizarCasosdeUso
  Time.Activities.EstructurarCasosdeUso -up-> "depends" Time.Activities.DetallarCasodeUso
  Time.Activities.PrototiparInterfazdeUsuario -up-> "depends" Time.Activities.DetallarCasodeUso



  Roles.SistemAnalist .up.> Time.Activities.EncontrarActoresyCasosdeUso
  Roles.SistemAnalist .up.> Time.Activities.EstructurarCasosdeUso
  Roles.Arquitech .up.> Time.Activities.PriorizarCasosdeUso
  Roles.UseCaseEspecificator .up.> Time.Activities.DetallarCasodeUso
  Roles.UIDesigner .up.> Time.Activities.PrototiparInterfazdeUsuario

@enduml