@startuml

Class AssignActivityController
Class CloseActivityController
Class MergeActivityController
Class OpenIterationController
Class ReestimateActivityController
Class SplitActivityController

@enduml
