@startuml
	class CreateUseCaseController {
	+createUseCase(useCase)
	}

	CreateUseCaseController --> UseCaseDao
	CreateUseCaseDialog --> CreateUseCaseController
	CreateUseCaseController ..> UseCase
@enduml
