@startuml
	class OpenUseCasesController {
	+getAllUseCases()
	}

	OpenUseCasesController o..> UseCase
	UseCasesManagementView --> OpenUseCasesController
	OpenUseCasesController --> UseCaseDao
@enduml
