@startuml
	class PrioritizeUseCaseController {
	+updateUseCase(useCase)
	}

	UseCasesManagementView --> PrioritizeUseCaseController
	PrioritizeUseCaseController --> UseCaseDao
	PrioritizeUseCaseController o..> UseCase
@enduml
