@startuml

skinparam NoteBackgroundColor #whiteSmoke

state 1 as " "
state 3 <<choice>>
state 6 as " :MEMBER_MANAGEMENT"

[*] --> 1
note on link
    User request delete any Member on project
end note
1 --> 3
note on link
    System shows member data to confirm delete
    * accept
    * decline/cancel
end note
3 --> 1
note on link
[pending activities or activities assigned]
end note
3 --> 6
note on link
System shows
* member was deleted
* show all members on project
end note
@enduml
