@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}

    state 0 as ":PROJECT_MANAGEMENT"
    state 1 as " "
    state 2 as ":USE_CASES_MANAGEMENT"
    state 3 as ":DISCIPLINES_MANAGEMENT"

    0 --> 1

    2 --> 1
    note on link
        User orders open members
    end note

    3 --> 1

    1 --> [*]
    note on link
        <b>System shows</b>
        * all members in the project, his names and roles
        <b>System allows</b>
        * create member
        * update member
        * delete member
        * open project
        * open iteration
        * open use cases
    end note

@enduml
