@startuml

state 0 as " :MEMBER:MANAGEMENT"
state 1 as " "
state 2 as " "
state 3 as " "
state 5 as " "
state 6 as " "
state 8 as " "
state 7 as " :MEMBER:MANAGEMENT"

skinparam {
    NoteBackgroundColor #whiteSmoke
}

0 --> 1
note on link
    User orders update member
end note

1 --> 2
note on link
<b>System shows</b>
* all members
<b>System allows</b>
* introduce a member to update
* cancel update member
end note

2 --> 3
note on link
    User introduces a member to update
end note

2 --> 8
note on link
    User orders cancel update member
end note

3 --> 5
note on link
<b>System shows</b>
* member name
* member roles
<b>System allows</b>
* introduce member name
* add member rol (duplicate roles not allowed)
* remove member rol (if member has any rol)
* cancel update member
* save changes
end note

5 --> 3
note on link
* User introduces member name
* User adds member rol
* User removes member rol
end note

5 --> 8
note on link
    User orders cancel update member
end note

8 --> 7
note on link
    <b>System shows</b>
    * all members in the project, his names and roles
    <b>System allows</b>
    * create member
    * update member
    * delete member
    * open project
    * open iteration
    * open use cases
end note

5 --> 6
note on link
    User orders save changes
end note

6 --> 7
note on link
    <b>System shows</b>
    * __member updated__
    * all members in the project, his names and roles
    <b>System allows</b>
    * create member
    * update member
    * delete member
    * open project
    * open iteration
    * open use cases
end note

@enduml
