@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
        ArrowColor #green
        NoteBorderColor #green
    }

state init as "MEMBER_MANAGEMENT"
state end as "MEMBER_MANAGEMENT"
init ---> DeleteMemberUseCase

note on link
    User request delete Member
end note

state DeleteMemberUseCase {
    state initial as " "
    state 6 as " "
    state 5 as " "
    [*]-->initial
    note on link
    <b>System required</b>
    * member (without AssignActivities)
    * Cancel
    end note

    5 --> [*]
    note on link
    <b>System show</b>
    * successfull
    end note


    initial-->5
    note on link
    <b>User provides</b>
    * member
    end note

    initial -[#red]-> 6
    note on link
    <b>User requests</b>
    * to cancel
    end note

    6 -[#red]-> [*]
    note on link
    <b>System shows</b>
    * operation cancelled
    end note

    DeleteMemberUseCase --> end
note on link
    <b>System shows</b>
    * all members in the project, his names and roles
    <b>System allows</b>
    * create member
    * update member
    * delete member
    * open project
    * open iteration
    * open use cases
end note
}
@enduml