@startuml

state 0 as " :MEMBER:MANAGEMENT"
state 7 as " :MEMBER:MANAGEMENT"

    skinparam {
        NoteBackgroundColor #whiteSmoke
        ArrowColor #green
        NoteBorderColor #green
    }

0 --> updateMember

state updateMember {

state 2 as " "
state 1 as " "
state 3 as " "
state 6 as " "


[*] --> 1
note on link
    User requests to update member
end note

1 --> 2
note on link
<b>System shows</b>
* all members
<b>System requests</b>
* Member to update
<b>System allows</b>
* cancel update member
end note

2 --> 3
note on link
    User provides a member to update
end note


3 --> 6
note on link
<b>System shows form</b>
*  name (required, unique)
*  List<role> (required)
end note


6 --> [*]
note on link
    <b>System shows</b>
    * member updated
end note

}

updateMember --> 7
note on link
    <b>System shows</b>
    * all members in the project, his names and roles
    <b>System allows</b>
    * create member
    * update member
    * delete member
    * open iterations
    * open iteration
    * open use cases
end note

@enduml
