@startuml

top to bottom direction
skinparam Linetype ortho
skinparam shadowing false
skinparam objectFontSize 18
scale max 1600 width

skinparam class {
  BackgroundColor<<Rol>> orchid
}

namespace role {
    Class role <<Rol>>
    Class SistemAnalist extends role
    Class Arquitect extends role
    Class UserCaseSpecificator extends role
    Class UIDesigner extends role
 }

namespace activity {
    Class activity <<(A,red)>>
    Class StructureUseCaseModel extends activity
    Class FindActorsAndUseCases extends activity
    Class PrioritizeUseCases extends activity
    Class DetailUseCases extends activity
    Class PrototypeUI extends activity
}    
    
    role.SistemAnalist --> "do" activity.FindActorsAndUseCases
    role.Arquitect --> "do" activity.PrioritizeUseCases
    role.Arquitect --> "do" activity.StructureUseCaseModel
    role.UserCaseSpecificator --> "do 1..N"  activity.DetailUseCases
    role.UIDesigner --> "do" activity.PrototypeUI

    activity.FindActorsAndUseCases <-- "depends on" activity.PrioritizeUseCases
    activity.PrioritizeUseCases <-- "depends on" activity.DetailUseCases
    activity.DetailUseCases <-- "depends on" activity.PrototypeUI
    activity.DetailUseCases <-- "depends on" activity.StructureUseCaseModel

@enduml