@startuml

top to bottom direction
skinparam Linetype ortho

skinparam class {
  BackgroundColor<<Rol>> orchid
}

namespace Role {
    Class Role <<Rol>>
    Class SistemAnalist extends Role
    Class Arquitect extends Role
    Class UserCaseSpecificator extends Role
    Class UIDesigner extends Role
 }

namespace Activity {
    Class Activity <<(A,red)>>
    Class StructureUseCaseModel extends Activity
    Class FindActorsAndUseCases extends Activity
    Class PrioritizeUseCases extends Activity
    Class DetailUseCases extends Activity
    Class PrototypeUI extends Activity

    FindActorsAndUseCases <-- "depends on" PrioritizeUseCases
    PrioritizeUseCases <-- "depends on" DetailUseCases
    DetailUseCases <-- "depends on" PrototypeUI
    DetailUseCases <-- "depends on" StructureUseCaseModel
}    
    
    Role.SistemAnalist --> "do" Activity.FindActorsAndUseCases
    Role.Arquitect --> "do" Activity.PrioritizeUseCases
    Role.Arquitect --> "do" Activity.StructureUseCaseModel
    Role.UserCaseSpecificator --> "do 1..N"  Activity.DetailUseCases
    Role.UIDesigner --> "do" Activity.PrototypeUI


@enduml