@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user

view PlanProjectView
model ProjectDao
controller PlanProjectController
model Project

user -right-> PlanProjectView
    note on link
        setStartDate(date startDate)
        setEndDate(date endDate)
        setCost(float cost)
        setIterationSize(int days)
        refreshEstimatedPhases(ProjectData)
        confirm()
        cancel()
    end note
PlanProjectView -right-> PlanProjectController
    note on link
        planProject(project)
    end note
PlanProjectController -right-> ProjectDao
    note on link
        create(project)
    end note

ProjectDao .down.> Project
PlanProjectController ..> Project
PlanProjectView ..> Project

@enduml
