@startuml

[*] --> OPENED_PROJECT : Open project
OPENED_PROJECT --> [*] : Close project
USE_CASES_MANAGEMENT --> [*] : Close project
RESOURCE_MANAGEMENT --> [*] : Close project
OPENED_CHRONOGRAPH --> [*] : Close project

[*] --> OPENED_PROJECT : Create project
OPENED_PROJECT --> OPENED_PROJECT : Save project
OPENED_PROJECT --> USE_CASES_MANAGEMENT : Show use cases
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Create use case \n Edit use case \n Delete use case \n Save project
USE_CASES_MANAGEMENT --> OPENED_PROJECT : Show project
OPENED_PROJECT --> RESOURCE_MANAGEMENT : Show resources
RESOURCE_MANAGEMENT --> RESOURCE_MANAGEMENT : Create resource \n Edit resource \n Delete resource \n Save project
RESOURCE_MANAGEMENT --> OPENED_PROJECT : Show project
OPENED_PROJECT --> OPENED_CHRONOGRAPH : Open iteration
OPENED_CHRONOGRAPH --> OPENED_CHRONOGRAPH : Assign activity \n Re-estimate activity \n Split activity \n Save project \n Combine activity
OPENED_CHRONOGRAPH --> OPENED_PROJECT : Show project
@enduml