@startuml
[*] --> OPENED_PROJECT : Open project
OPENED_PROJECT --> [*] : Close project
USE_CASES_MANAGEMENT --> [*] : Close project
RESOURCE_MANAGEMENT --> [*] : Close project
OPENED_CHRONOGRAPH --> [*] : Close project
[*] --> OPENED_PROJECT : Create project
OPENED_PROJECT --> OPENED_PROJECT : Save project
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Save project
RESOURCE_MANAGEMENT --> RESOURCE_MANAGEMENT : Save project
OPENED_CHRONOGRAPH --> OPENED_CHRONOGRAPH : Save project
OPENED_PROJECT --> USE_CASES_MANAGEMENT : Show use cases
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Create use case
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Edit use case
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Delete use case
USE_CASES_MANAGEMENT --> USE_CASES_MANAGEMENT : Prioritize use case
USE_CASES_MANAGEMENT --> OPENED_PROJECT : Open project
OPENED_PROJECT --> RESOURCE_MANAGEMENT : Show resources
RESOURCE_MANAGEMENT --> RESOURCE_MANAGEMENT : Create resource
RESOURCE_MANAGEMENT --> RESOURCE_MANAGEMENT  : Edit resource
RESOURCE_MANAGEMENT --> RESOURCE_MANAGEMENT : Delete resource
RESOURCE_MANAGEMENT --> OPENED_PROJECT : Open project
OPENED_PROJECT --> OPENED_CHRONOGRAPH : Project planning
OPENED_CHRONOGRAPH --> OPENED_CHRONOGRAPH : Assign activity
OPENED_CHRONOGRAPH --> OPENED_CHRONOGRAPH : Re-estimate activity
OPENED_CHRONOGRAPH --> OPENED_CHRONOGRAPH : Split activity
OPENED_CHRONOGRAPH --> OPENED_PROJECT : Open project
@enduml