@startuml

top to bottom direction
skinparam Linetype ortho

View *-- UseCaseModelView

UseCaseModelView *- "1" index
UseCaseModelView *-- "1..*" UseCase
UseCaseModelView *-- "1..*" Actor
UseCaseModelView "*" -- "*" UserInterfacePrototype
index .[#000000].> UseCase
index .[#000000].> UseCaseContext
index .[#000000].> UserInterfacePrototype
index .[#000000].> Actor
UseCaseContext o-- "1..*" UseCase
UseCaseModelView *-- "1" UseCaseContext
UseCase *-- "0..1" UseCaseSpecification
UserInterfacePrototype .[#000000].> UseCase
UseCase --> "Structure" UseCase
Actor "*" --o "*" UseCase


@enduml