@startuml

!include ../configuration/skinParams.puml
!include ../configuration/definitions.puml

actor user
view IterationView
controller AssignActivityController
model ActivityDao
model Activity

user -down-> IterationView
note on link
    assignActivityToMember(activityId, memberId)
end note
IterationView -right-> AssignActivityController
note on link
    assignActivityToMember(activity, member)
end note
AssignActivityController --> ActivityDao
note on link
    save(activity)
end note

AssignActivityController --> Activity
note on link
    setMember(member)
end note
ActivityDao ..> Activity
@enduml
