@startuml
skinparam NoteBackgroundColor #whiteSmoke

state USECASE_MANAGEMENT_END as ":USECASE_MANAGEMENT"

USECASE_MANAGEMENT --> prioritizeUseCases

state prioritizeUseCases {

state 1 as " " #LawnGreen
state 2 as " " #LawnGreen
state 8 as " " #LawnGreen
state 9 as " " #LawnGreen
state 10 as " " #LawnGreen
state 11 as " " #LawnGreen
state 12 as " " #LawnGreen
state 13 as " "


[*] --> 1
note on link
    User requests to prioritize use cases
end note

1 --> 2
note on link
<b>System requires</b>
* the use case to be prioritized
end note

2 --> 8
note on link
<b>User provides</b>
* a use case to be prioritized
end note

8 --> 9
note on link
<b>System shows</b>
* provided use case prioritization
<b>System requires</b>
* the priority for the use case
<b>System allows</b>
* cancel
end note

9 --> 10
note on link
    <b>User provides</b>
    * the priority for the use case
end note

10 --> 11
note on link
    <b>System requires</b>
    * confirm
    * cancel
end note

11 --> 12
note on link
    <b> User requests to </b>
    * confirm
end note

12 --> [*]
note on link
    <b>System shows</b>
    * Use case has been prioritized
end note

'Variation path
9 --> 13
note on link
    <b>User requests to</b>
    * cancel
end note
11 --> 13
note on link
    <b>User requests to</b>
    * cancel
end note

13 --> [*]
note on link
<b>System shows</b>
* prioritization cancelled
end note

prioritizeUseCases --> USECASE_MANAGEMENT_END
note on link
<b>System shows</b>
* all use cases sorted by priority
** highest priority in the top, lowest in the button
** use case without priority has the lowest priority
<b>System allows</b>
* Prioritize Use cases
* Create use case
* Update use case
* Delete use case
* Open iteration
* Open iterations
* Open members
* Close system
end note
@enduml
