@startuml
    state 1 as " "
    state 2 as " "
    state 0 as " "
    state 4 as " "
    state 6 as " "
    state 5 as ":OPENED_ITERATION"
    state 3 <<choice>>
    state 13 as ":OPENED_ITERATION"

    5 --> 6
    note on link
        Manager orders split activity
    end note

    6 --> 2
    note on link
        System shows
        * not assigned to member chips/pills
        System allows
        * select chip to split
        * cancel split
    end note
    2 --> [*]
    note on link
    Manager orders cancel split
    end note
    2 --> 3
    note on link
        Manager selects activity to split
    end note
    3 --> 4
    3 --> [*]
    note on link
    [activity assigned to member]
    end note
    4 --> 0
    note on link
        System shows
        * highlighted the activity to assign
        System allows
        * confirm split
        * cancel split
    end note
    0 --> [*]
    note on link
    Manager orders cancel split
    end note

    0 --> 1
    note on link
        Manager orders confirm split activity
    end note
    1 --> 13
    note on link
        System shows
        * 1 column for each discipline and inside
        * selected pill 1 hour smaller
        * a new pill with the size of 1 hour on top of the selected pill
    end note
@enduml
