@startuml
!include ../StateDiagramsSetUp.puml

state PROJECT_MANAGEMENTEND as ":PROJECT_MANAGEMENT"
state INIT_PROJECTSTART as ":INIT_PROJECT"
state INIT_PROJECTEND as ":INIT_PROJECT"

INIT_PROJECTSTART --> PlanProject

state PlanProject {
    state 1 as " "
    state 2 as " "
    state 3 <<choice>>
    state 4 as " "
    state 5 as " "
    state 6 as " "
    state 10 as " "

    [*] --> 1
    note on link
        User requests to plan project
    end note

    1 --> 2
    note on link
    <b>System requires</b>
    * start project date
    * end project date
    * project cost
    <b>System allows</b>
    * confirm step
    * cancel
    end note

    2 --> 3
   note on link
        <b>User provides</b>
        * start date
        * end date
        * project cost
    end note

    2 -[#red]-> 10
    note on link
        User requests to cancel
    end note


    3 -[#red]-> 1
    note on link
        [end date before start date
        OR start date after end date
        OR cost <= 0
        OR start end date interval < 10 days]
    end note

    3 --> 4

    4 --> 5
    note on link
        <b>System shows</b>
        * nº iterations in project (10 iterations by default)
        * iteration duration (in days)
        * each phase start end dates
        <b>System allows</b>
        * change nº iteration in project
        **[ +/- 10 iterations ]
        **[ minimum 10 iteration in project ]
        **[ maximum iterations as the nº iterations (10 days duration) that not exceeds project end date ]
        **[ minimum iteration duration 10 days]
        * confirm planned project
        * cancel
    end note

    5 -[#red]-> 10
    note on link
        User requests to cancel
    end note

    10 -[#red]-> INIT_PROJECTEND
    note on link
    <b>System allows</b>
    * plan project
    * open phases
    end note

    5 --> 4
    note on link
    <b>User provides</b>
    * new nº of iterations in project
    end note

    5 --> 6
    note on link
        User requests to confirm planned project
    end note

    6 --> PROJECT_MANAGEMENTEND
      note on link
              <b>System shows</b>
              * the project was successfully planned
              * project information
              <b>System allows</b>
              * Open phases
              * Open iterations
              * Open iteration [iterations opened]
              * Open members
              * Open usecases
              * close system
          end note
}

INIT_PROJECTEND -[#red]-> [*]
PROJECT_MANAGEMENTEND --> [*]




@enduml
