@startuml
!include skinParams.puml

    'analysis
    package analysis {
        boundary XView #9FB7E5
        control XController #C4E4AB
        entity XEntity #F8D987
        entity XDao #F8D987

        XView -down-> XController
        XView -down-> XEntity
        XController .down.> XEntity
        XController -down-> XDao
    }
    'Design
    package front <<angular:10>>{

        rectangle presentation {
            rectangle xComponent {
               boundary XTemplate <<HTML>>
               boundary XStyle <<CSS>>
               boundary XComponent <<TypeScript>>
            }
            control HTTPService
            control XAngularService <<TypeScript>>
            control XViewModel
            entity XRestRepository
        }


        entity XDao <<TypeScript>>

        rectangle logic {
            control XLogicService as "XController" <<TypeScript>>
            entity XModel
            entity XTSDao as "XRepository"
        }


        XComponent -down-> XAngularService
        XComponent -down-> XViewModel
        XComponent -right-> XModel
        XRestRepository ..|> XTSDao
        XRestRepository --> HTTPService
        XAngularService ..> XRestRepository
        XAngularService ..> XLogicService
        XAngularService ..> XViewModel
        XLogicService ..> XTSDao
        XLogicService --> XModel
        XTSDao -down--> XModel
        XTemplate -down- XComponent
        XTemplate -right-> XStyle
    }

    package backend <<spring:5.3>> {
        entity XResource
        entity XBService
        entity XRepository
        entity XDto
        entity XBEntity
        XResource --> XBService
        XResource --> XDto
        XBService --> XBEntity
        XBService --> XDto
        XBService --> XRepository
        XRepository --> XBEntity
    }


    XDao <.[#Gray].. XResource: <<trace>>


    XEntity <.[#Gray].. XBEntity: <<trace>>
    XEntity <.[#Gray].. XModel: <<trace>>

    XController <.[#Gray].. XLogicService <<trace>>
    XController <.[#Gray].. XAngularService <<trace>>
    XView <.[#Gray]. XComponent
    XDao <.[#Gray].. XTSDao: <<trace>>
@enduml
