@startuml

!include skinParams.puml

    'analysis
    package analysis {
        boundary XView #9FB7E5
        control XController #C4E4AB
        entity XEntity #F8D987
        entity XDao #F8D987

        XView -down-> XController
        XView -down-> XEntity
        XController .down.> XEntity
        XController -down-> XDao
    }
    'Design
    package front <<angular:10>>{
        rectangle component {
           boundary XTemplate <<HTML>>
           boundary XStyle <<CSS>>
           boundary XComponent <<TypeScript>>
           XComponent .> XTemplate
           XComponent <- XTemplate
           XTemplate --> XStyle
        }
        boundary XModel
        control XService <<TypeScript>>
        entity HTTPService
        XComponent -left-> XService
        XComponent --> XModel
        XService --> XModel
        XService o-- HTTPService
    }

    package backend <<spring:5.3>> {
        control XResource
        control XBService
        entity XRepository
        entity XDto
        entity XBEntity
        XResource --> XBService
        XResource --> XDto
        XBService --> XBEntity
        XBService --> XDto
        XBService --> XRepository
        XRepository --> XBEntity
    }



    XTemplate ...[#Gray]up.> XView : <<trace>>
    XStyle ...[#Gray]up.> XView : <<trace>>
    XComponent ...[#Gray]up.> XView : <<trace>>

    XService ...[#Gray]up.> XController : <<trace>>
    XService .[#Gray]right.> XResource : <<trace>>

    XResource ...[#Gray]up.> XDao : <<trace>>
    XBService ...[#Gray]up.> XDao : <<trace>>
    XRepository ...[#Gray]up.> XDao : <<trace>>

    XDto ...[#Gray]up.> XEntity : <<trace>>
    XBEntity ...[#Gray]up.> XEntity : <<trace>>

@enduml
