@startuml

namespace components {
    class Menu

    class UseCaseManagement <<component>>
    class UseCaseDialog <<component>>

    class MembersManagement <<component>>
    class MemberDialog <<component>>

    class ProjectManagementView <<component>>

    components.Menu .down.> components.UseCaseManagement
    components.Menu .down.> components.MembersManagement
    components.Menu .down.> components.ProjectManagementView

    UseCaseManagement .down.> UseCaseDialog
    MembersManagement .down.> MemberDialog
}

components.MembersManagement -down-> services.MemberService
components.MemberDialog -down-> services.MemberService

components.UseCaseManagement -down-> services.UseCaseService
components.UseCaseDialog -down-> services.UseCaseService

namespace services {
    class MemberService
    class UseCaseService
}

components -down[hidden]> services

@enduml
