@startuml
scale 1200 width
package models {
    abstract class Activity
    abstract Class Phase
    abstract class Discipline
    class Member
    class rol
    class UseCase extends RequirimentActivity
    class Project
    class System
	class Iteration extends Phase
	class Inception extends Phase
	class Elaboration extends Phase
	class Construction extends Phase
	class Transition extends Phase
	class RequerimentDiscipline extends Discipline
	class AnalisisDiscipline extends Discipline
	class DesignDiscipline extends Discipline
	class ImplementationDiscipline extends Discipline
	class TestDiscipline extends Discipline
    class RequirimentActivity extends Activity
    class AnalysisActivity extends Activity
    class DesignActivity extends Activity
    class ImplementationActivity extends Activity
    class TestActivity extends Activity

	Phase o-- Iteration
}

@enduml
