@startuml

  set namespaceSeparator .

  Disciplines.BussinessEngineering <-left- Time.Activities.DomainModel

  Time.Activities.DomainModel -> Artifacts.DomainModel

  Time.Activities.DomainModel <.left. Roles.DomainExpert
  Time.Activities.DomainModel <.left. Roles.DomainAnalist

  Roles.DomainExpert "helps" ..> Roles.DomainAnalist 
  Roles.DomainAnalist "generates" ..> Artifacts.DomainModel
    
  namespace Artifacts {
    namespace UMLDiagrams {
    }
    DomainModel <-- "0..*" Artifacts.UMLDiagrams.ClassDiagram
    DomainModel <-- "0..*" Artifacts.UMLDiagrams.ObjectDiagram
    DomainModel <-- "0..*" Artifacts.UMLDiagrams.StateDiagram
    DomainModel <-- "0..*" Artifacts.UMLDiagrams.ClassDiagram
    DomainModel <-- "as needed" UMLDiagram
  }

@enduml