@startuml


actor user
boundary IterationView
control AssignActivityController
entity ActivityDao
entity Activity
entity MemberDao
entity Member

user -down-> IterationView
    note on link
        assignActivityToMember(activityId, memberId)
    end note

IterationView -right-> AssignActivityController
    note on link
        assignActivityToMember(activityId, memberId)
    end note

AssignActivityController -right-> ActivityDao
    note on link
        getById(activityId)
        save(activity)
    end note
AssignActivityController .> Activity
    note on link
        setMember(member)
    end note
AssignActivityController -down-> MemberDao
    note on link
        getById(memberId)
    end note
AssignActivityController .down.> Member
MemberDao .> Member

ActivityDao ..> Activity
Member <- Activity
@enduml
