@startuml
    skinparam {
        NoteBackgroundColor #whiteSmoke
    }

    state 0 as ":ITERATION_MANAGEMENT"
    state 1 as " "
    state 5 as " "
    state 13 as " "
    state 14 as " "
    state 20 as " "
    state 15 <<choice>>
    state 12 as ":ITERATION_MANAGEMENT"

    0 --> 1
    note on link
        User orders assign NotAssignedActivity
    end note

    1 --> 13
    note on link
    <b>System shows</b>
    * for each member
    **assignedActivities in his datetime until end of current iteration
    * for each discipline (requirements, analysis, design, implementation)
    ** NotAssignedActivities (with activity type)
    <b>System allows</b>
    * introduce NotAssignedActivity to be assigned
    * cancel assign activity
    end note

    13 --> 5
    note on link
        User
        * introduces NotAssignedActivity
        * and orders confirm selection
    end note

    13 --> 20
    note on link
        User orders cancel assign activity
    end note

    5 --> 14
    note on link
    <b>System shows</b>
    * NotAssignedActivity
    ** duration (in hours)
    ** activity type
    * for each member
    **assignedActivities in his datetime until end of current iteration
    <b>System allows</b>
    * introduce assign destination
    ** specific member hour without assignedActivity
    * cancel assign activity
    end note

    14 -down-> 15
    note on link
        * User introduces assign destination
        * and orders confirm selection
    end note

    14 --> 20
    note on link
    User orders cancel assign activity
    end note

    20 --> 12
    note on link
         <b>System shows</b>
         * __assign activity cancelled__
         * for each member
         **assignedActivities in his datetime until end of current iteration
         * for each discipline (requirements, analysis, design, implementation)
         ** NotAssignedCost
         ** NotAssignedActivities (with activity type)
         <b>System allows</b>
         * Split activity
         * Assign activity
         * Re-estimate activity
         * Merge activity
         * Open project
         * Open members
         * Close system
    end note

    15 --> 5
    note on link
        [NotAssignedActivity duration > member assign destination of not assigned time until next assignedActivity
        OR
        NotAssignedActivity overlaps member max capacity (hours) in current iteration]
    end note

    15 --> 12
    note on link
     <b>System shows</b>
     * __NotAssignedActivity was assigned to member__
     * for each member
     **assignedActivities in his datetime until end of current iteration
     * for each discipline (requirements, analysis, design, implementation)
     ** NotAssignedCost
     ** NotAssignedActivities (with activity type)
     <b>System allows</b>
     * Split activity
     * Assign activity
     * Re-estimate activity
     * Merge activity
     * Open project
     * Open members
     * Close system
     end note
@enduml
