@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}

    state 0 as ":ITERATION_MANAGEMENT" #LawnGreen
    state 1 as " "  #LawnGreen
    state 5 as " "  #LawnGreen
    state 13 as " "  #LawnGreen
    state cancel as " "
    state 12 as ":ITERATION_MANAGEMENT"
    state PROJECT_MANAGEMENT as ":PROJECT_MANAGEMENT" #LawnGreen


    0 --> 1
    note on link
        User orders Close iteration
    end note

    1 --> 13
    note on link
    <b>System shows</b>
    * nº AssignedActivity closed
    * nº AssignedActivity not closed
    * cost/hours consumed in current iteration
    * cost/hours not consumed in current iteration
    * for each discipline
    ** NotAssignedCost
    <b>System allows</b>
    * order confirm close iteration
    * cancel close iteration
    end note

    13 --> cancel
    note on link
        User orders cancel close iteration
    end note

    13 --> 5
    note on link
        User orders confirm close iteration
    end note


    cancel --> 12
    note on link
         <b>System shows</b>
         * __Close activity cancelled__
         * for each member
         **assignedActivities in his datetime until end of current iteration
         * for each discipline (requirements, analysis, design, implementation)
         ** NotAssignedCost
         ** NotAssignedActivities (with activity type)
         <b>System allows</b>
         * Split activity
         * Assign activity
         * Re-estimate activity
         * Merge activity
         * Open project
         * Open members
         * Close system
    end note


    5 --> PROJECT_MANAGEMENT
    note on link
    <b>System shows</b>
    * project information
    ** name
    ** start date
    ** end date
    ** name
    ** duration (business days)
    ** progress (business days)
    ** iteration duration (business days)
    <b>System allows</b>
    * Open phases
    * Open iterations
    * Open iteration
    * Open members
    * Open usecases
    * close system
    end note
@enduml
