@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}

    state ITERATION_MANAGEMENT_START as ":ITERATION_MANAGEMENT" #LawnGreen
    state ITERATION_MANAGEMENT_END as ":ITERATION_MANAGEMENT" #LawnGreen

    ITERATION_MANAGEMENT_START --> CloseActicity
    note on link
        User requests to close activity
    end note


    state CloseActicity {
        state 5 as " " #LawnGreen
        state 13 as " " #LawnGreen
        state 14 as " " #LawnGreen
        state alternativeWay as " "
        state 15 as " " #LawnGreen

    [*] --> 13
    note on link
    <b>System shows</b>
    * for each member
    **assignedActivities in his datetime until end of current iteration
    <b>System requires</b>
    * AssignedActivity to be closed
    <b>System allows</b>
    * confirm step
    * cancel close activity
    end note

    13 --> alternativeWay
    note on link
        User requires to cancel close activity
    end note

    13 --> 5
    note on link
        User
        * introduces AssignedActivity
        * and requires to confirm step
    end note

    5 --> 14
    note on link
    <b>System shows</b>
    * AssignedActivity information
    ** discipline
    ** member name
    ** member rol
    ** start datetime
    ** expected end datetime
    ** expected duration in hours
    <b>System requires</b>
    * real AssignedActivity duration in hours
    ** only positive numbers, max 100 hours
    <b>System allows</b>
    * confirm close activity
    * cancel close activity
    end note

    14 --> alternativeWay
    note on link
        User requests to cancel close activity
    end note

    14 --> 5
    note on link
        User introduces real AssignedActivity duration in hours
    end note

    14 -down-> 15
    note on link
        User requests to confirm close activity
    end note

    alternativeWay --> [*]
    note on link
         <b>System shows</b>
         * Close activity operation cancelled
    end note

    15 --> [*]
    note on link
     <b>System shows</b>
     * AssignedActivity has been closed
     end note

     }

     CloseActicity -down-> ITERATION_MANAGEMENT_END
         note on link
          <b>System shows</b>
          * for each member
          **assignedActivities in his datetime until end of current iteration
          * for each discipline (requirements, analysis, design, implementation)
          ** NotAssignedCost
          ** NotAssignedActivities (with activity type)
          <b>System allows</b>
          * Split activity
          * Assign activity
          * Re-estimate activity
          * Merge activity
          * Open iterations
          * Open members
          * Close system
          end note


@enduml
