@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}

    state 0 as ":OPENED_DISCIPLINES"
    state 1 as " "
    state 5 as " "
    state 13 as " "
    state 14 as " "
    state 20 as " "
    state 15 as " "
    state 12 as ":OPENED_DISCIPLINES"

    0 --> 1
    note on link
        User orders merge AssignedActivity
    end note

    1 --> 13
    note on link
    <b>System shows</b>
    * for each member
    **assignedActivities in his datetime until end of current iteration
    * for each discipline (requirements, analysis, design, implementation)
    ** NotAssignedCost
    <b>System allows</b>
    * introduce AssignedActivity to be merged
    * cancel merge activity
    end note

    13 --> 5
    note on link
        User
        * introduces AssignedActivity
        * and orders confirm selection
    end note

    13 --> 20
    note on link
        User orders cancel merge activity
    end note

    5 --> 14
    note on link
    <b>System shows</b>
    * for each discipline (requirements, analysis, design, implementation)
    ** NotAssignedCost
    <b>System allows</b>
    * introduce NotAssignedCost as merge destination
    * cancel merge activity
    end note

    14 --> 20
    note on link
        User orders cancel merge activity
    end note

    14 -down-> 15
    note on link
        * User introduces merge destination
        * and orders confirm selection
    end note

    20 --> 12
    note on link
         <b>System shows</b>
         * for each member
         **assignedActivities in his datetime until end of current iteration
         * for each discipline (requirements, analysis, design, implementation)
         ** NotAssignedCost
         ** NotAssignedActivities (with activity type)
         <b>System allows</b>
         * Split activity
         * Assign activity
         * Re-estimate activity
         * Merge activity
         * Open project
         * Open members
         * Close system
    end note


    15 --> 12
    note on link
     <b>System shows</b>
     * AssignedActivity was returned to NotAssignedCost
     * for each member
     **assignedActivities in his datetime until end of current iteration
     * for each discipline (requirements, analysis, design, implementation)
     ** NotAssignedCost
     ** NotAssignedActivities (with activity type)
     <b>System allows</b>
     * Split activity
     * Assign activity
     * Re-estimate activity
     * Merge activity
     * Open project
     * Open members
     * Close system
     end note
@enduml
