@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}

    state 0 as ":PROJECT_MANAGEMENT"
    state 1  <<choice>>
    state 2 as ":USE_CASES_MANAGEMENT"
    state 3 as ":MEMBERS_MANAGEMENT"
    state 4 as " " #LawnGreen
    state 5 as " " #LawnGreen
    state 6 as " " #LawnGreen
    state 7 <<choice>>
    state 9 as " " #LawnGreen
    state 10 as " "
    state 11 as " "



    0 --> 1
    note on link
        User orders open iteration
    end note
    2 --> 1
    note on link
        User orders open iteration
    end note
    3 --> 1
    note on link
        User orders open iteration
    end note
    1 --> 4
    note on link
        [empty iteration]
    end note
    4 --> 6
    note on link
        * <b>System shows</b>
        ** use cases ordered by prioritization
        * <b>System allows</b>
        ** introduce use case for the current iteration
        ** introduce this use cases desired realization
        *** REQUIREMENTS | ANALYSIS | DESIGN | IMPLEMENTATION
        ** order confirm open iteration
        ** open project
    end note

    6 --> 11
    note on link
        User orders to open project
    end note

    11 --> PROJECT_MANAGEMENT
    note on link
    <b>System shows</b>
    * project information
    ** name
    ** start date
    ** end date
    ** name
    ** duration (business days)
    ** progress (business days)
    ** iteration duration (business days)
    <b>System allows</b>
    * Open phases
    * Open iterations
    * Open iteration
    * Open members
    * Open usecases
    * close system
    end note


    6 --> 4
    note on link
        * User introduces use case for the current iteration
        * User introduces use cases desired realization
    end note
    6 --> 7
    note on link
        User orders confirm open iteration
    end note
    7 --> 9
    note on link
    [usecases introduced >= 1
    AND
    all use cases introduced have desired realization]
    end note
    9--> 5
    note on link
        <b>System shows</b>
        * NotAssignedCost for each discipline have been generated
    end note
    7 --> 10
    10 --> 4
    note on link
        <b>System shows</b>
        * more than one usecases should be introduced
        * some use case has not desired realization
    end note
    1 --> 5
    note on link
        [Iteration opened]
    end note
    5 --> [*]
    note on link
     <b>System shows</b>
     * for each member
     **assignedActivities in his datetime until end of current iteration
     * for each discipline (requirements, analysis, design, implementation)
     ** NotAssignedCost
     ** NotAssignedActivities (with activity type)
     <b>System allows</b>
     * Split activity
     * Assign activity
     * Re-estimate activity
     * Merge activity
     * Open project
     * Open members
     * Close system
    end note
@enduml
