@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}

state 12 as ":PROJECT_MANAGEMENT"

    0 --> OpenIteration
    2 --> OpenIteration
    note on link
        User requests to open iteration
    end note
    3 --> OpenIteration

state ITERATION_MANAGEMENT as ":ITERATION_MANAGEMENT"
state 2 as ":USE_CASES_MANAGEMENT"
state 3 as ":MEMBERS_MANAGEMENT"

    state 0 as ":PROJECT_MANAGEMENT"
state OpenIteration {

    state 1  <<choice>>
    state 4 as " " #LawnGreen
    state 6 as " " #LawnGreen
    state 7 <<choice>>
    state 9 as " " #LawnGreen
    state 10 as " "
    state 11 as " "
    state PROJECT_MANAGEMENT as ":PROJECT_MANAGEMENT"

    [*] --> 1

    1 --> 4
    note on link
        [empty iteration]
    end note
    4 --> 6
    note on link
        <b>System shows</b>
        ** use cases ordered by prioritization
        <b>System requires</b>
        * use cases for the current iteration
        ** and his desired realization
        *** REQUIREMENTS | ANALYSIS | DESIGN | IMPLEMENTATION
        <b>System allows</b>
        * Confirm open iteration
        * cancel
    end note

    6 --> 11
    note on link
        User requests to cancel
    end note

    11 --> [*]
    note on link
    <b>System shows</b>
    * operation cancelled
    end note

    6 --> 4
    note on link
        * User introduces use case for the current iteration
        * and his desired realization
    end note
    6 --> 7
    note on link
        User requests to confirm open iteration
    end note
    7 --> 9
    note on link
    [usecases introduced >= 1
    AND
    all use cases introduced have desired realization]
    end note
    9--> [*]
    note on link
        <b>System shows</b>
        * NotAssignedCost for each discipline have been generated
    end note
    7 --> 10
    10 --> 4
    note on link
        <b>System shows</b>
        * more than one usecases should be introduced
        * some use case has not desired realization
    end note
    1 --> [*]
    note on link
        [Iteration opened]
    end note
}

OpenIteration --> 12
note on link
        (from cancel operation)
        <b>System shows</b>
        * for each iteration in project ordered by number ASC
        ** start date
        ** end date
        ** duration (bussiness days)
        ** dias transcurridos (bussiness days) and his percentage
        <b>System allows</b>
        * Open project
        * Open openPhases
        * Open iteration
        * Open usecases
        * Open members
        * Close system
end note

OpenIteration --> ITERATION_MANAGEMENT
    note on link
     <b>System shows</b>
     * for each member
     **assignedActivities in his datetime until end of current iteration
     * for each discipline (requirements, analysis, design, implementation)
     ** NotAssignedCost
     ** NotAssignedActivities (with activity type)
     <b>System allows</b>
     * Split activity
     * Assign activity
     * Re-estimate activity
     * Merge activity
     * Open Iterations
     * Open members
     * Close system
    end note

@enduml
