@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}


    state 5 as ":ITERATION_MANAGEMENT"
    state 13 as ":ITERATION_MANAGEMENT"

    state SplitActivity {
        state 2 as " " #LawnGreen
        state 0 as " " #LawnGreen
        state 4 as " " #LawnGreen
        state 6 as " " #LawnGreen
        state 8 as " " #LawnGreen
        state 10 as " "
    }

    5 --> 6
    note on link
        User orders split activity
    end note

    6 --> 2
    note on link
    <b>System shows</b>
    * for each discipline (requirements, analysis, design, implementation)
    ** NotAssignedCost
    <b>System requires</b>
    * introduce NotAssignedCost to split
    <b>System allows</b>
    * confirm step
    * cancel split activity
    end note

    2 --> 10
    note on link
        User orders cancel split
    end note

    2 --> 4
    note on link
        * User introduces NotAssignedCost to split
        * and orders confirm
    end note

    4 --> 0
    note on link
        <b>System shows</b>
        * NotAssignedCost available hours
        <b>System requires</b>
        * introduce NotAssignedActivity information
        ** Activity type: one of the RUP identified activities of the introduced NotAssignedCost discipline
        ** NotAssignedActivity description
        <b>System allows</b>
        * confirm step
        * cancel split activity
    end note

    0 --> 10
    note on link
        User orders cancel split
    end note

    0 --> 8
    note on link
        User introduces
        * NotAssignedActivity type
        * NotAssignedActivity description
        and orders confirm split
    end note

    8 --> 13
    note on link
        <b>System shows</b>
        * __NotAssignedCost split successful__
        * for each member
        **assignedActivities in his datetime until end of current iteration
        * for each discipline (requirements, analysis, design, implementation)
        ** NotAssignedCost
        ** NotAssignedActivities (with activity type)
        <b>System allows</b>
        * Split activity
        * Assign activity
        * Re-estimate activity
        * Merge activity
        * Open project
        * Open members
        * Close system
    end note

    10 --> 13
    note on link
         <b>System shows</b>
         * __split activity was cancelled__
         * for each member
         **assignedActivities in his datetime until end of current iteration
         * for each discipline (requirements, analysis, design, implementation)
         ** NotAssignedCost
         ** NotAssignedActivities (with activity type)
         <b>System allows</b>
         * Split activity
         * Assign activity
         * Re-estimate activity
         * Merge activity
         * Open project
         * Open members
         * Close system
    end note

    13 --> [*]

@enduml
