@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}


    state ITERATION_MANAGEMENT_STARTS as ":ITERATION_MANAGEMENT"
    state ITERATION_MANAGEMENT_ENDS as ":ITERATION_MANAGEMENT"


    ITERATION_MANAGEMENT_STARTS --> SplitActivity
    note on link
        User requests to split activity
    end note

    state SplitActivity {
        state 2 as " " #LawnGreen
        state 0 as " " #LawnGreen
        state 4 as " " #LawnGreen
        state 8 as " " #LawnGreen
        state 10 as " "


    [*] --> 2
    note on link
    <b>System shows</b>
    * for each discipline (requirements, analysis, design, implementation)
    ** NotAssignedCost
    <b>System requires</b>
    * introduce NotAssignedCost to split
    <b>System allows</b>
    * confirm step
    * cancel split activity
    end note

    2 --> 10
    note on link
        User requests to cancel split
    end note

    2 --> 4
    note on link
        * User introduces NotAssignedCost to split
        * and requests to confirm
    end note

    4 --> 0
    note on link
        <b>System shows</b>
        * NotAssignedCost available hours
        <b>System requires</b>
        * introduce NotAssignedActivity information
        ** Activity type: one of the RUP identified activities of the introduced NotAssignedCost discipline
        ** NotAssignedActivity description
        <b>System allows</b>
        * confirm step
        * cancel split activity
    end note

    0 --> 10
    note on link
        User requests to cancel split
    end note

    0 --> 8
    note on link
        User introduces
        * NotAssignedActivity type
        * NotAssignedActivity description
        and requests to confirm split
    end note

    8 --> [*]
    note on link
        <b>System shows</b>
        * __NotAssignedCost split successful__
    end note

    10 --> [*]
    note on link
         <b>System shows</b>
         * __split activity was cancelled__
    end note

    }


    SplitActivity --> ITERATION_MANAGEMENT_ENDS
    note on link
             <b>System shows</b>
             * for each member
             **assignedActivities in his datetime until end of current iteration
             * for each discipline (requirements, analysis, design, implementation)
             ** NotAssignedCost
             ** NotAssignedActivities (with activity type)
             <b>System allows</b>
             * Split activity
             * Assign activity
             * Re-estimate activity
             * Merge activity
             * Open members
             * Close system
        end note

@enduml
