@startuml
top to bottom direction
skinparam Linetype ortho
skinparam shadowing false
skinparam objectFontSize 16
scale max 1980 width
title Domain Model RUP Management

object project
object phase
object team
object calendar
object process
object iteration
object activity
object inception
object elaboration
object construction
object transition
object requirements
object domainModel
object glossary
object diagrams
object role
object DomainModelDiagram
object SourceCode
object member
object artifact
object UseCase
object customer
object AnalyzeArchitecture
object AnalyzeUseCases
object AnalyzeClasses
object AnalyzePackages
object DesignArchitecture
object DesignClass
object DesignUseCase
object DesignSubsystems
object analysis
object design
object FindActorsAndUseCases
object PrioritizeUseCases
object DetailUseCases
object PrototypeUI
object StructureUseCaseModel
object NonFuncionalRequirements
object ImplementArchitecture
object IntegrateSystems
object ImplementClass
object ImplementSubsystem
object UnitTesting
object cascade
object task
object taskRequirements
object taskAnalyze
object taskDesign
object taskImplement
object taskTesting
object taskDeploy


phase <|-[#374F6B]- inception
inception *-d- requirements
requirements *-- FindActorsAndUseCases
requirements *-- PrioritizeUseCases  
requirements *-- StructureUseCaseModel
requirements *-- DetailUseCases
requirements *-- PrototypeUI
phase <|-[#374F6B]- elaboration


phase <|-[#374F6B]- construction
phase <|-[#374F6B]- transition

project "1" *-- "1" inception 
requirements .[#000000].> domainModel

project "1" *-- "1" elaboration
project "1" *-- "1" construction
project "1" *-- "1" transition
project *-- team
project o-- calendar
team "1" *-- "N" member
role <|-[#374F6B]- member


process "1" *-- "N" activity
FindActorsAndUseCases -[#374F6B]-|> process 
PrioritizeUseCases -[#374F6B]-|> process 
DetailUseCases -[#374F6B]-|> process 
PrototypeUI -[#374F6B]-|> process 
StructureUseCaseModel -[#374F6B]-|> process 

inception *-- domainModel
domainModel o-- glossary
domainModel "1" *-- "N" DomainModelDiagram 


elaboration .[#000000].> inception
elaboration *-- analysis
design .[#000000].> analysis
analysis *-- AnalyzeArchitecture
AnalyzeArchitecture *-- NonFuncionalRequirements
AnalyzeArchitecture .[#000000].> domainModel
AnalyzeArchitecture .[#000000].> StructureUseCaseModel
analysis *-d- AnalyzeUseCases
analysis *-d- AnalyzeClasses
analysis *-d- AnalyzePackages
AnalyzeArchitecture -[#374F6B]-|> process 
AnalyzeUseCases -[#374F6B]-|> process 
AnalyzeClasses -[#374F6B]-|> process 
AnalyzePackages -[#374F6B]-|> process 
AnalyzeArchitecture <.[#000000]. AnalyzeUseCases
AnalyzeUseCases <.[#000000]. AnalyzeClasses
AnalyzeClasses <.[#000000]. AnalyzePackages
elaboration *-- design
design *-d- DesignArchitecture
design *-d- DesignClass
design *-d- DesignUseCase
design *-d- DesignSubsystems
DesignArchitecture -[#374F6B]-|> process 
DesignClass -[#374F6B]-|> process 
DesignUseCase -[#374F6B]-|> process 
DesignSubsystems -[#374F6B]-|> process 
DesignArchitecture <.[#000000]. DesignClass
DesignArchitecture <.[#000000]. DesignUseCase
DesignClass <.[#000000]. DesignUseCase
DesignClass <.[#000000]. DesignSubsystems
DesignUseCase <.[#000000]. DesignSubsystems
activity "1" *-- "1" cascade
cascade o-d- taskRequirements
cascade o-d- taskAnalyze
cascade o-d- taskDesign
cascade o-d- taskImplement
cascade o-d- taskTesting
cascade o-d- taskDeploy
taskRequirements -[#374F6B]-|> task 
taskAnalyze -[#374F6B]-|> task 
taskDesign -[#374F6B]-|> task 
taskImplement -[#374F6B]-|> task 
taskTesting -[#374F6B]-|> task 
taskDeploy -[#374F6B]-|> task 
taskRequirements <.[#000000]. taskAnalyze
taskAnalyze <.[#000000]. taskDesign
taskDesign <.[#000000]. taskImplement
taskImplement <.[#000000]. taskTesting
taskTesting <.[#000000]. taskDeploy


construction .d.> elaboration
construction *-d- ImplementArchitecture
construction *-d- IntegrateSystems
construction *-d- ImplementClass
construction *-d- ImplementSubsystem
construction *-d- UnitTesting
ImplementArchitecture -[#374F6B]-|> process 
IntegrateSystems -[#374F6B]-|> process 
ImplementClass -[#374F6B]-|> process 
ImplementSubsystem -[#374F6B]-|> process 
UnitTesting -[#374F6B]-|> process 
ImplementArchitecture <.[#000000]. IntegrateSystems
IntegrateSystems <.[#000000]. ImplementClass 
IntegrateSystems <.[#000000]. ImplementSubsystem
ImplementClass <.[#000000]. UnitTesting
ImplementSubsystem <.[#000000]. UnitTesting
ImplementSubsystem <.[#000000]. ImplementClass 
transition .[#000000].> construction

iteration "N" --o "1" phase
domainModel -[#374F6B]-|>process
member --o activity 
activity <|-[#374F6B]- glossary
activity <|-[#374F6B]- DomainModelDiagram

artifact <|-[#374F6B]- UseCase
artifact <|-[#374F6B]- SourceCode
artifact <|-[#374F6B]- diagrams
DomainModelDiagram *-- diagrams
activity "1" *-- "N" artifact
domainModel o-- customer : Collaboration


FindActorsAndUseCases <.[#000000]. PrioritizeUseCases
PrioritizeUseCases <.[#000000]. DetailUseCases
DetailUseCases <.[#000000]. PrototypeUI
DetailUseCases <.[#000000]. StructureUseCaseModel

calendar .[#000000].> iteration
calendar .[#000000].> member


calendar : Represents Iterations Schedule
calendar : Represents Members Timetable
iteration : N days interval
activity : estimated time
activity : real time
activity : status

 
@enduml
