@startuml
top to bottom direction
skinparam Linetype ortho

Class Project
Class Phase
Class Iteration
Class Activity
Class Discipline
Class UseOfCase
Class Member
Class Role

Project *--> Phase
Phase *-> Iteration
Iteration *-> Activity
Activity <-* Discipline
UseOfCase <-- Activity
Project *--> UseOfCase

Project *---> Member
Member *-> Role
Activity o--> Role

Activity --> Member

@enduml
