@startuml

top to bottom direction
skinparam Linetype ortho

namespace Resources {
    
'Objects
Class Team
Class Cost
Class WorkingDaysMonth
Class WorkingHoursDays
Class ContractType
Class Holidays
Class Rol
Class Member

Team *- JornadaLaboral
Team *-down- "1..*" Member

JornadaLaboral *-- WorkingDaysMonth
JornadaLaboral *-- WorkingHoursDays

Member "0..*" o- "0..* skills" Rol
Member *-down- Cost : cost/hour
Member *-left- ContractType
Member *-- Holidays
Member *-- WorkLog

}

@enduml
