@startuml

top to bottom direction
skinparam Linetype ortho

namespace Resources {
    
    namespace Roles {
      Class Rol
    }

'Objects
Class Team
Class Cost
Class WorkingDaysMonth
Class WorkingHoursDays
Class ContractType
Class Holidays

Class Activities.Activity
Class Member

Team *- JornadaLaboral
Team *-down- "1..*" Member
JornadaLaboral *-- WorkingDaysMonth
JornadaLaboral *-- WorkingHoursDays
Activities.Activity o-- "required Rol" Resources.Roles.Rol
Member --o Activities.Activity
Member "0..*" o- "0..* skills" Resources.Roles.Rol
Member *-down- Cost : cost/hour
Member *-left- ContractType
Member *-- Holidays
}

@enduml