@startuml

namespace Resources {
  Class Rol
 
  namespace Roles {
    Class ProjectManager extends Resources.Rol
    Class SistemAnalist extends Resources.Rol
    Class Arquitech extends Resources.Rol
    Class UseCaseEspecificator extends Resources.Rol
    Class ComponentEngineer extends Resources.Rol
    Class TestEngineer extends Resources.Rol
    Class SystemIntegrator extends Resources.Rol
    Class IntegrationTestEngineer extends Resources.Rol
    Class SystemTestEngineer extends Resources.Rol
    Class UseCaseEngineer extends Resources.Rol
    Class UIDesigner extends Resources.Rol
  }
}
@enduml