@startuml

skinparam Linetype ortho

namespace Time {
  Abstract Class Activity

  namespace Activities {

    Class EncontrarActoresyCasosdeUso extends Time.Activity
    Class PriorizarCasosdeUso extends Time.Activity
    Class DetallarCasodeUso extends Time.Activity
    Class EstructurarCasosdeUso extends Time.Activity
    Class PrototiparInterfazdeUsuario extends Time.Activity
    
    Class AnalisisdelaArquitectura extends Time.Activity
    Class AnalisisdeCasodeUso extends Time.Activity
    Class AnalisisdeClase extends Time.Activity
    Class AnalisisdePaquete extends Time.Activity
    
    Class DisenyodelaArquitectura extends Time.Activity
    Class DisenyodeCasodeUso extends Time.Activity
    Class DisenyodeClase extends Time.Activity
    Class DisenyodePaquete extends Time.Activity
    
    Class ImplementarlaArquitectura extends Time.Activity
    Class IntegraciondeSistemas extends Time.Activity
    Class ImplementarClase extends Time.Activity
    Class PruebasUnitarias extends Time.Activity
    Class ImplementarSubsistema extends Time.Activity
    
    Class PlanificarPruebas extends Time.Activity
    Class DisenyarPruebas extends Time.Activity
    Class ImplementarPruebas extends Time.Activity
    Class RealizarPruebasdeIntegracion extends Time.Activity
    Class RealizarPruebasdeSistemas extends Time.Activity
    Class EvaluarPruebas extends Time.Activity
  }
}

Disciplines.Reruirements <-down- Time.Activities.EncontrarActoresyCasosdeUso
Disciplines.Reruirements <-down- Time.Activities.PriorizarCasosdeUso
Disciplines.Reruirements <-down- Time.Activities.DetallarCasodeUso
Disciplines.Reruirements <-down- Time.Activities.EstructurarCasosdeUso
Disciplines.Reruirements <-down- Time.Activities.PrototiparInterfazdeUsuario

Disciplines.Analysis <-down- Time.Activities.AnalisisdelaArquitectura
Disciplines.Analysis <-down- Time.Activities.AnalisisdeCasodeUso
Disciplines.Analysis <-down- Time.Activities.AnalisisdeClase
Disciplines.Analysis <-down- Time.Activities.AnalisisdePaquete

Disciplines.Design <-down- Time.Activities.DisenyodelaArquitectura
Disciplines.Design <-down- Time.Activities.DisenyodeCasodeUso
Disciplines.Design <-down- Time.Activities.DisenyodeClase
Disciplines.Design <-down- Time.Activities.DisenyodePaquete

Disciplines.Implementation <-down- Time.Activities.ImplementarlaArquitectura
Disciplines.Implementation <-down- Time.Activities.IntegraciondeSistemas
Disciplines.Implementation <-down- Time.Activities.ImplementarClase
Disciplines.Implementation <-down- Time.Activities.PruebasUnitarias
Disciplines.Implementation <-down- Time.Activities.ImplementarSubsistema

Disciplines.Test <-down- Time.Activities.PlanificarPruebas
Disciplines.Test <-down- Time.Activities.DisenyarPruebas
Disciplines.Test <-down- Time.Activities.ImplementarPruebas
Disciplines.Test <-down- Time.Activities.RealizarPruebasdeIntegracion
Disciplines.Test <-down- Time.Activities.RealizarPruebasdeSistemas
Disciplines.Test <-down- Time.Activities.EvaluarPruebas



    Time.Activity o-down- "uses" Artifacts.Artifact
    Time.Activity o-down- "creates" Artifacts.Artifact
    Time.Activity o-down- "modifies" Artifacts.Artifact
    
@enduml