@startuml

top to bottom direction

namespace Artifacts {
    Abstract Class Artifact
    Class UseCaseModelView extends Artifact
    Class DesignModelView extends Artifact
    Class ImplementationView extends Artifact
    Class DeploymentView extends Artifact
    Class ProcessView extends Artifact

    'TODO: del diagrama de marcos

    'Class Codigo extends Artifact
    'Class Diagrams.Diagram extends Artifact
    
}

@enduml