@startuml

Class Diagram
Class StructureDiagram extends Diagram
Class ComportamientoDiagram extends Diagram
Class ClassDiagram
Class ObjectDiagram
Class ComponentDiagram
Class DeployDiagram
Class PackageDiagram
Class UseCaseDiagram
Class ActivityDiagram
Class StateDiagram
Class InteractionDiagram
Class SequenceDiagram
Class CommunicationDiagram

StructureDiagram <|-- ClassDiagram
StructureDiagram <|-- ObjectDiagram
StructureDiagram <|-- ComponentDiagram
StructureDiagram <|-- DeployDiagram
StructureDiagram <|-- PackageDiagram

ComportamientoDiagram <|-- UseCaseDiagram
ComportamientoDiagram <|-- ActivityDiagram
ComportamientoDiagram <|-- StateDiagram
ComportamientoDiagram <|-- InteractionDiagram

InteractionDiagram <|-- CommunicationDiagram
InteractionDiagram <|-- SequenceDiagram

@enduml