@startuml

namespace Artifacts {
  Abstract Class UMLDiagram

    namespace UMLDiagrams {
    
    Class Estructural extends Artifacts.UMLDiagram
    Class Comportamiento extends Artifacts.UMLDiagram
    Class ClassDiagram
    Class ObjectDiagram
    Class ComponentDiagram
    Class DeployDiagram
    Class PackageDiagram
    Class ComplexStructureDiagram

    Class UseCaseDiagram
    Class ActivityDiagram
    Class StateDiagram
    Class InteractionDiagram
    
    Class SequenceDiagram
    Class CommunicationDiagram
    Class TimeDiagram
    Class GeneralInteractionDiagram

    Estructural <|-- ClassDiagram
    Estructural <|-- ObjectDiagram
    Estructural <|-- ComponentDiagram
    Estructural <|-- DeployDiagram
    Estructural <|-- PackageDiagram
    Estructural <|-- ComplexStructureDiagram

    Comportamiento <|-- UseCaseDiagram
    Comportamiento <|-- ActivityDiagram
    Comportamiento <|-- StateDiagram
    Comportamiento <|-- InteractionDiagram
    
    InteractionDiagram <|-- CommunicationDiagram
    InteractionDiagram <|-- SequenceDiagram
    InteractionDiagram <|-- TimeDiagram
    InteractionDiagram <|-- GeneralInteractionDiagram
    }
}

@enduml