@startuml

top to bottom direction
skinparam Linetype ortho

Abstract Class Time.Activity

namespace Disciplines {
    Abstract Class Discipline
    Class DomainModelDiscipline extends Discipline
    Class RequirementsDiscipline extends Discipline
    Class AnalysisDiscipline extends Discipline
    Class DesignDiscipline extends Discipline
    Class ImplementationDiscipline extends Discipline
    Class TestDiscipline extends Discipline

    DomainModelDiscipline <-- "depends on" RequirementsDiscipline
    RequirementsDiscipline <-- "depends on" AnalysisDiscipline
    AnalysisDiscipline <-- "depends on" DesignDiscipline
    DesignDiscipline <-- "depends on" ImplementationDiscipline
    ImplementationDiscipline <-- "depends on" TestDiscipline

   'TODO: Faltan disciplinas por poner en el diagrama de marcos
   'existen Gestion, Despliegue, Entorno y Versionar

    Discipline *-- Time.Activity 
}




@enduml