@startuml

top to bottom direction
skinparam Linetype ortho

namespace Phases {
    Class Phase
    Class InceptionPhase extends Phase
    Class ElaborationPhase extends Phase
    Class ConstructionPhase extends Phase
    Class TransitionPhase extends Phase

    InceptionPhase <-- "depends on" ElaborationPhase
    ElaborationPhase <-- "depends on" ConstructionPhase
    ConstructionPhase <-- "depends on" TransitionPhase
}

@enduml