@startuml

  set namespaceSeparator .
  
  Time.Activities.DomainModel   ..> "next" Time.Activities.EncontrarActoresyCasosdeUso
  Time.Activities.EncontrarActoresyCasosdeUso <.right. Roles.SistemAnalist
  Time.Activities.EncontrarActoresyCasosdeUso ..> "next" Time.Activities.PriorizarCasosdeUso
  
  Time.Activities.EncontrarActoresyCasosdeUso <.. Artifacts.ListaCaracteristicas
  Time.Activities.EncontrarActoresyCasosdeUso <.. Artifacts.RequisitosSuplementarios
  Time.Activities.EncontrarActoresyCasosdeUso <.. Artifacts.DomainModel

  Time.Activities.EncontrarActoresyCasosdeUso .> Artifacts.UseCaseView
  Time.Activities.EncontrarActoresyCasosdeUso .> Artifacts.Glosary

  namespace Artifacts {
    namespace UMLDiagrams {
    }
    UseCaseView <-- "1..*" Artifacts.UMLDiagrams.UseCaseDiagram
    UseCaseView <-- "0..*" Artifacts.UMLDiagrams.StateDiagram
    UseCaseView <-- "0..*" Artifacts.UMLDiagrams.PackageDiagram
    UseCaseView <-- "as needed" UMLDiagram
  }

@enduml