@startuml

  set namespaceSeparator .
  
  Time.Activities.DetallarCasodeUso ..> "next" Time.Activities.EstructurarCasosdeUso
  Time.Activities.EstructurarCasosdeUso <.right. Roles.SistemAnalist
  Time.Activities.EstructurarCasosdeUso ..> "next" Time.Activities.xxxxxx 
  'TODO: definir el next de  Time.Activities.xxxxxx 
  
  Time.Activities.EstructurarCasosdeUso <.. Artifacts.UseCaseView
  Time.Activities.EstructurarCasosdeUso <.. Artifacts.RequisitosSuplementarios
  Time.Activities.EstructurarCasosdeUso <.. Artifacts.DetalledUseCase
  Time.Activities.EstructurarCasosdeUso <.. Artifacts.Glosary

  Time.Activities.EstructurarCasosdeUso .> Artifacts.StructuredUseCase

  namespace Artifacts {
    namespace UMLDiagrams {
    }
    StructuredUseCase <-- "1..*" Artifacts.UMLDiagrams.UseCaseDiagram
    StructuredUseCase <-- "0..*" Artifacts.UMLDiagrams.StateDiagram
    StructuredUseCase <-- "0..*" Artifacts.UMLDiagrams.PackageDiagram
    'StructuredUseCase <-- "0..*" Artifacts.UMLDiagrams.SequenceDiagram
    'StructuredUseCase <-- "0..*" Artifacts.UMLDiagrams.ActivityDiagram
    'StructuredUseCase <-- "0..*" Artifacts.UMLDiagrams.InteractionDiagram
    StructuredUseCase <-- "as needed" UMLDiagram
  }

@enduml