@startuml

  set namespaceSeparator .
  
  Time.Activities.EncontrarActoresyCasosdeUso   ..> "next" Time.Activities.PriorizarCasosdeUso
  Time.Activities.PriorizarCasosdeUso <.right. Roles.Arquitech
  Time.Activities.PriorizarCasosdeUso ..> "next" Time.Activities.DetallarCasodeUso
  
  Time.Activities.PriorizarCasosdeUso <.. Artifacts.UseCaseView
  Time.Activities.PriorizarCasosdeUso <.. Artifacts.RequisitosSuplementarios
  Time.Activities.PriorizarCasosdeUso <.. Artifacts.Glosary

  Time.Activities.PriorizarCasosdeUso .> Artifacts.ArquitectureDescription

  Time.Activities.PriorizarCasosdeUso <.. Risks

  note "Tomar en consideración:\n•Aspectos técnicos\n•Aspectos de redundancia\n•Aspectos económicos\n•Aspectos de negocio\n•Aspectos obscuros de requisitos" as N2

@enduml