@startuml

  set namespaceSeparator .
  
  Time.Activities.DetallarCasodeUso ..> "next" Time.Activities.PrototiparInterfazdeUsuario
  Time.Activities.PrototiparInterfazdeUsuario <.right. Roles.UIDesigner
  Time.Activities.PrototiparInterfazdeUsuario .right.> "next" Disciplines.Analisys
  
  Time.Activities.PrototiparInterfazdeUsuario <.. Artifacts.UseCaseView
  Time.Activities.PrototiparInterfazdeUsuario <.. Artifacts.RequisitosSuplementarios
  Time.Activities.PrototiparInterfazdeUsuario <.. Artifacts.DetalledUseCase
  Time.Activities.PrototiparInterfazdeUsuario <.. Artifacts.Glosary

  Time.Activities.PrototiparInterfazdeUsuario .> Artifacts.UIPrototype

  namespace Artifacts {
    UIPrototype <-- "1" Artifacts.SourceCode
    UIPrototype <-- "1..*" Artifacts.Executable
    UIPrototype <-- "1..*" UMLDiagram
  }

@enduml