@startuml
!procedure _deleteMemberUI()
 {+
    
        {^"Delete: marco@rupman.com"
            {#
                    <color:red><b>Are you sure? 
                    <color:gray>This action cannot be reverted
            }
        }

        {+ [<&plus> Confirm] | [<&x> Cancel]}
    }
 }
!endprocedure
@enduml