@startuml
!procedure _initProject()
{^"app"
    {+

    {^  "(<i><color:blue>optional)"
        {^"Project"
          Start Date    | 10-10-2020
          End Date    | 10-12-2020
          Progress | 12 / 54 days
          Iteration size | 10 days
          [Open]
        }
    }

        {+ [<&plus> Plan project] | [<&x> close]}
    }

}
!endprocedure
@enduml
