!procedure _prioritizeUsecasesUI()
 {+
            {^"project"
                {#
                    <b>Usecase | <b>priorization
                    planProject | "10"
                    openIteration | "8"
                    assignActivity | "7"
                    createMember | "_"
                    openUsecases | "_"
                }
            }
        {+ [cancel] | [ confirm priorization ]}
    }
!endprocedure
