@startuml
!procedure _updateMemberUI()
{^"Xabi b - xabi@rupman.com"
    {+

   
        {^"Update Member"
          Name    | "Xabi            "
          Surname    | "B               "
          Email | "xabi@rupman.com    "
          Weekly cost (h) | "40              "
          Role |  ^Architect^
        }
   

        {+ [<&plus> Save] | [<&x> Cancel]}
    }

}
!endprocedure
@enduml