@startuml

state editUseCase {
    state 1 <<choice>>
    state 2 <<choice>>
    state 3 <<choice>>
    state 4 <<choice>>
    state 5 <<choice>>
    state 6 <<choice>>
    state 7 <<choice>>

    [*] --> 1 : Manager request to open use cases
    1 --> 2 : System shows all use of cases
    2 --> 3 : Manager select a \n use case
    3 --> 4 : Manager request to edit \n the selected use case
    4 --> 5 : System allows\nto modify the information\nfor the use case
    5 --> 6 : Manager modify the\n use case information
    6 --> 7 : Manager request\nto save the use case information
    7 -left-> 2 : Manager request \nto cancel the \nuse case edition
    7 --> 2 : System save the use case
}

@enduml
