@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
}
package INIT_PROJECT {
  usecase "Start System" as StartSystem #LawnGreen
}

package PROJECT_MANAGEMENT {
  usecase "Plan Project" as PlanProject  
  usecase "Open Phases" as OpenPhases #LawnGreen
  note right: [[./InitProjectNavigation.puml View]]
  usecase "Open Iterations" as OpenIterations    
}

package USE_CASES_MANAGEMENT {
  usecase "Create Use Case" as CreateUseCase
  usecase "Update Use Case" as UpdateUseCase
  usecase "Delete Use Case" as DeleteUseCase
  usecase "Prioritize Use Cases" as PrioritizeUseCases
}
package ITERATION_MANAGEMENT {
  usecase "Open Iteration" as OpenIteration #LawnGreen
  usecase "Assign Activity" as AssignActivity
  usecase "Re-estimate Activity" as ReestimateActivity
  usecase "Split Activity" as SplitActivity
  usecase "Merge Activity" as MergeActivity  
  
}
package MEMBER_MANAGEMENT {
  usecase "Create Member" as CreateMember
  usecase "Delete Member" as DeleteMember  
}
INIT_PROJECT --> PlanProject
INIT_PROJECT --> OpenPhases 
note on link
[exists(project)]
endnote
PlanProject -> OpenPhases
OpenPhases --> OpenIterations
OpenIterations --> OpenPhases
OpenIteration <-- OpenIterations


   

@enduml