@startuml
left to right direction
skinparam {
    NoteBackgroundColor #whiteSmoke
}
title
 <u>User Interfaces Navigation Index</u>
end title
package INIT_PROJECT {
  usecase "Start System" as StartSystem #LawnGreen
  note right: [[./InitProjectNavigation.puml View]]
}

package PROJECT_MANAGEMENT {
  usecase "Plan Project" as PlanProject  
  usecase "Open Phases" as OpenPhases #LawnGreen
  note right: [[./ProjectManagementNavigation.puml View]]
  usecase "Open Iterations" as OpenIterations    
}
package MEMBER_MANAGEMENT {
  usecase "Create Member" as CreateMember
  usecase "Delete Member" as DeleteMember  
  usecase "Update Member" as UpdateMember
  usecase "Open Members" as OpenMembers  #LawnGreen
  note right: [[./InitProjectNavigation.puml View]]
}
package ITERATION_MANAGEMENT {
  usecase "Open Iteration" as OpenIteration #LawnGreen
  note right: [[./InitProjectNavigation.puml View]]
  usecase "Assign Activity" as AssignActivity
  usecase "Re-estimate Activity" as ReestimateActivity
  usecase "Split Activity" as SplitActivity
  usecase "Merge Activity" as MergeActivity    
}
package USE_CASES_MANAGEMENT {
  usecase "Create Use Case" as CreateUseCase
  usecase "Update Use Case" as UpdateUseCase
  usecase "Delete Use Case" as DeleteUseCase
  usecase "Prioritize Use Cases" as PrioritizeUseCases
  usecase "Open Use Cases" as OpenUseCases #LawnGreen
  note right: [[./InitProjectNavigation.puml View]]
}


usecase "Close System" as CloseSystem

INIT_PROJECT --> PlanProject 
PlanProject --> OpenPhases: [Planned]
INIT_PROJECT --> OpenPhases :[exists(project)]
INIT_PROJECT -down--> CloseSystem
PROJECT_MANAGEMENT -down-->  CloseSystem
USE_CASES_MANAGEMENT -down-->  CloseSystem
MEMBER_MANAGEMENT -down-->  CloseSystem
ITERATION_MANAGEMENT -down--> CloseSystem

OpenPhases <-down-> OpenIterations
OpenIteration <--> OpenIterations
OpenIteration <--> AssignActivity
OpenIteration <--> SplitActivity
OpenIteration <--> MergeActivity
OpenIteration <--> ReestimateActivity

OpenUseCases <--> PrioritizeUseCases
OpenUseCases <--> CreateUseCase
OpenUseCases <--> UpdateUseCase
OpenUseCases <--> DeleteUseCase

PROJECT_MANAGEMENT -[hidden]-> MEMBER_MANAGEMENT
   

@enduml