@startuml

!include procedures/SaltProcedure.puml
!include procedures/InitProject.puml

(*) -down-> SALT(initProject)
(*) -down-> SALT(initProjectWithoutProject)
initProject --> (*)
initProjectWithoutProject --> (*)


@enduml


