@startuml

!include procedures/SaltProcedure.puml
!include procedures/ProjectManagement.puml
!include procedures/PlanProject.puml
!include procedures/InitProject.puml

skinparam {
    NoteBackgroundColor #whiteSmoke
    StateBackgroundColor #green
}

(*) -down-> SALT(initProject) #LawnGreen
initProject -right-> SALT(planProject)
    note on link
    plan project
    end note
planProject -left-> SALT(initProject)
    note on link
    cancel
    end note
planProject -down-> SALT(projectManagement) #LawnGreen


@enduml


