@startuml

!include procedures/SaltProcedure.puml
!include procedures/project/ProjectManagement.puml
!include procedures/project/PlanProject.puml
!include procedures/project/InitProject.puml
!include procedures/usecases/UsecasesManagementUI.puml
!include procedures/usecases/CreateUsecaseUI.puml
!include procedures/usecases/DeleteUsecaseUI.puml
!include procedures/usecases/UpdateUsecaseUI.puml
!include procedures/usecases/PrioritizeUsecasesUI.puml
!include procedures/members/MemberManagement.puml
!include procedures/members/CreateMemberUI.puml
!include procedures/members/DeleteMemberUI.puml
!include procedures/members/UpdateMemberUI.puml

skinparam {
    NoteBackgroundColor #whiteSmoke
    StateBackgroundColor #green
}

(*) -down-> "<img:https://share.balsamiq.com/c/riuCQFtjDogoQoA2p7YgUB.png>" as initProject #LawnGreen
initProject -right-> "<img:https://share.balsamiq.com/c/dsbQacGeZgtcfZhQpgesHi.png>" as planProject
    note on link
        plan project
    end note

planProject -right-> "<img:https://share.balsamiq.com/c/qJoFTguYy77vzgiYemSEj6.png>" as planProject2

planProject2 -down-> "<img:https://share.balsamiq.com/c/o6eJ12SWA1sigq7na7iuEg.png>" as projectManagement #LawnGreen
note on link
    openPhases
end note

projectManagement -right-> SALT(memberManagement) #LawnGreen
    note on link
        openMembers
    end note

memberManagement --> SALT(createMemberUI)
note on link
    create member
end note

memberManagement --> SALT(deleteMemberUI)
note on link
    delete member
end note

memberManagement --> SALT(updateMemberUI)
note on link
    update member
end note

projectManagement -left-> SALT(usacasesManagement) #LawnGreen
note on link
    openUsecases
end note

usacasesManagement --> SALT(createUsecaseUI)
note on link
    create usecase
end note

usacasesManagement --> SALT(deleteUsecaseUI)
note on link
    delete usecase
end note

usacasesManagement --> SALT(updateUsecaseUI)
note on link
    update usecase
end note

usacasesManagement --> SALT(prioritizeUsecasesUI)
note on link
 prioritize Usecases
end note

projectManagement -down-> "<img:https://share.balsamiq.com/c/6e6SMgKPvjCdVPsDgyFv5w.png>" as iterationManagement #LawnGreen
note on link
    open iteration
end note

iterationManagement -left-> "<img:https://share.balsamiq.com/c/qJYZaLz8NqAdeFjKJASEVB.png>" as splitActivity
note on link
    split activity
end note

iterationManagement -down-> "<img:https://share.balsamiq.com/c/c1bQ5MuY6C5Md2UM777s1w.png>" as reestimaeteActivity
note on link
    re estimate activity
end note

reestimaeteActivity -down-> "<img:https://share.balsamiq.com/c/9uQNnhyt3rtyhKqaxBxSAt.png>" as reestimaeteActivity2

iterationManagement -down-> "<img:https://share.balsamiq.com/c/qNLm4uBkSCzAhXH9ZkoT5B.png>" as mergeActivity
note on link
    merge activity
end note

iterationManagement -down-> "<img:https://share.balsamiq.com/c/9gJgaXEo55Z6VXgciWYB49.png>" as assignActivity
note on link
    assign activity
end note


iterationManagement -right-> "<img:https://share.balsamiq.com/c/gJ7qYvK2VEuuNAFAFjJtwo.png>" as closeActivity
note on link
    close activity
end note

closeActivity -right-> "<img:https://share.balsamiq.com/c/9UKQQiTsruF5q3LnkgbTmC.png>" as closeActivity2

closeActivity2 -right-> "<img:https://share.balsamiq.com/c/nPUu3xKwZ4epXSKbip5RYs.png>" as closeActivity3

@enduml


