@startuml

skinparam {
    NoteBackgroundColor #whiteSmoke
    StateBackgroundColor #green
}

(*) -down-> "<img:https://share.balsamiq.com/c/riuCQFtjDogoQoA2p7YgUB.png>" as initProject #LawnGreen

initProject -down-> "<img:https://share.balsamiq.com/c/iZj7bpXJVoWa47qPr5dMwV.png>" as projectManagement #LawnGreen

projectManagement -right-> "<img:https://share.balsamiq.com/c/gViP8S2Mu926xNmkKzMXp9.png>" #LawnGreen

projectManagement -left-> "<img:https://share.balsamiq.com/c/m8ZYkthpBqcxEXcjKaZuHk.png>" #LawnGreen

projectManagement -down-> "<img:https://share.balsamiq.com/c/6e6SMgKPvjCdVPsDgyFv5w.png>" as iterationManagement #LawnGreen
note on link
    open iteration
end note

@enduml


