@startuml

!include procedures/SaltProcedure.puml
!include procedures/ProjectManagement.puml
!include procedures/PlanProject.puml
!include procedures/InitProject.puml

(*) -down-> SALT(initProject) #LawnGreen
initProject -right-> SALT(planProjectBasicInfo)
    note on link
    plan project
    end note
planProjectBasicInfo -left-> SALT(initProject)
    note on link
    cancel
    end note
planProjectBasicInfo -down-> SALT(planProjectIterationSize)
planProjectIterationSize -left-> initProject
    note on link
    cancel
    end note
planProjectIterationSize -down-> SALT(projectManagement) #LawnGreen


@enduml


