@startuml

top to bottom direction
skinparam Linetype ortho

'Objects
Class Project
Abstract Class Time.Phase
Class Time.Iteration
Class Time.IterationDiscipline
Class Resources.Rol
Class Resources.Team
Class Risks.Risk
Class Artifacts.Artifact

Abstract Class Time.Activity
Class Resources.Member

Project *-- Risks.Risk
Project *-- "1" Resources.Team
Project *-- Artifacts.Artifact
Project *-- "4" Time.Phase
Time.Phase *-- "1..*" Time.Iteration
Time.Iteration *-- "1..*" Time.IterationDiscipline
Time.IterationDiscipline *-- "enum" Time.DisciplineType
Time.IterationDiscipline *- "1..*" Time.Activity
Resources.Team *-- "1..*" Resources.Member
Resources.Member *-- "1" Resources.WorkLog
Resources.WorkLog --> "0..*" Time.Activity
Time.Activity o-- Resources.Rol
Resources.Member o-- Resources.Rol

@enduml