@startuml

top to bottom direction
skinparam Linetype ortho

'Objects
Class Project
Abstract Class Time.Phase
Class Time.Iteration
Class Time.Discipline
Class Resources.Rol
Class Resources.Team
Class Risks.Risk
Class Artifacts.Artifact
Abstract Class Time.Activity
Class Resources.Member

Project *-- Risks.Risk
Project *-- "1" Resources.Team
Project *-- Artifacts.Artifact
Project *-- "4" Time.Phase

Time.Phase *-- "1..*" Time.Iteration
Time.Iteration *-- "1..*" Time.Discipline
Time.Discipline *- "1..*" Time.Activity

Resources.Team *-- "1..*" Resources.Member
Resources.Member *-- "1" Resources.JornadaLaboral
Resources.Member *-- Resources.Rol

Artifacts.Artifact *-- Artifacts.UseCaseView
Artifacts.Artifact *-- Artifacts.DesignView
Artifacts.Artifact *-- Artifacts.ImplementationView
Artifacts.Artifact *-- Artifacts.DeploymentView
Artifacts.Artifact *-- Artifacts.ProcessView
@enduml