@startuml

top to bottom direction
skinparam Linetype ortho

'Objects
Class Project
Class Phases.Phase
Class Iteration
Class IterationDiscipline
Class Resources.Roles.Rol
Class Resources.Team
Class Risk
Class Artifacts.Artifact

Class Activities.Activity
Class Resources.Member

Project *-- Risk
Project *-- "1" Resources.Team
Project *-- Artifacts.Artifact
Project *-- "4" Phases.Phase
Phases.Phase *-- "1..*" Iteration
Iteration *-- "1..*" IterationDiscipline
IterationDiscipline *-- "enum" DisciplineType
IterationDiscipline *- "1..*" Activities.Activity
Resources.Team *-- "1..*" Resources.Member
Activities.Activity "1..*" o- "1..*" Resources.Member
Activities.Activity o-- Resources.Roles.Rol
Resources.Member o-- Resources.Roles.Rol

@enduml