@startuml
top to bottom direction
skinparam Linetype ortho

Class Project
Class Phase
Class Iteration
Class Discipline
Class Activity

Project *-- "4" Phase
Phase *-- "1..*" Iteration
Iteration *-- "1..*" Activity
Activity *-- "1" Discipline

Iteration -[hidden]> Activity
@enduml
