@startuml
!procedure _createMemberUI()
{^""
    {+

   
        {^"Create Member"
          Name    | "alpha           "
          Surname    | "alpha           "
          Email | "Valid email     "
          Weekly cost (h) | "accept int > 0  "
          Role |  ^Select a role^
        }
   

        {+ [<&plus> Save] | [<&x> Cancel]}
    }

}
!endprocedure
@enduml