@startuml

Abstract Class Discipline
Class RequerimentDiscipline
Class AnalisisDiscipline
Class DesignDiscipline
Class ImplementationDiscipline
Class TestDiscipline

Discipline <|-- RequerimentDiscipline
Discipline <|-- AnalisisDiscipline
Discipline <|-- DesignDiscipline
Discipline <|-- ImplementationDiscipline
Discipline <|-- TestDiscipline

@enduml
