@startuml

Class System
Class Project
Class Iteration
Abstract Class Phase
Class Inception
Class Elaboration
Class Construction
Class Transition

Phase <|-- Inception
Phase <|-- Elaboration
Phase <|-- Construction
Phase <|-- Transition

Phase o-- Iteration

@enduml