@startuml
skinparam {
    NoteBackgroundColor #whiteSmoke
}
    state PROJECT_MANAGEMENT as ":PROJECT_MANAGEMENT"
    state 2 as ":PROJECT_MANAGEMENT"

    PROJECT_MANAGEMENT --> OpenIterations
    note on link
        User orders Open Iterations
    end note


    state OpenIterations {
        state 1 as " "
            [*] --> 1

            1 --> [*]
    }

    OpenIterations --> 2
            note on link
                <b>System shows</b>
                * for each iteration in project ordered by number ASC
                ** start date
                ** end date
                ** duration (bussiness days)
                ** dias transcurridos (bussiness days) and his percentage
                <b>System allows</b>
                * Open openPhases
                * __Open iteration__
                * Open usecases
                * Open members
                * Close system
            end note


@enduml
