name: Unit & Integration Tests

on:
  workflow_dispatch:  # Permite ejecución manual
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test
        run: mvn clean verify -f rup-projects-core/

      - name: Build Angular App
        run: |
          cd web-app
          npm install
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rupprojectstile392/rup-projects:${{ github.sha }},rupprojectstile392/rup-projects:latest

      - name: Create compose file for distribution
        run: |
          cat > compose.yaml <<EOF
          services:
            rup-projects:
              image: rupprojectstile392/rup-projects:latest
              container_name: rup-projects-app
              ports:
                - "80:80"
                - "8080:8080"
              restart: unless-stopped
          EOF

      - name: Publish Docker Compose as OCI artifact
        run: |
          docker compose -f compose.yaml publish rupprojectstile392/rup-projects-compose:latest
          docker compose -f compose.yaml publish rupprojectstile392/rup-projects-compose:${{ github.sha }}


