@startuml
top to bottom direction
skinparam Linetype ortho

'Time
Time.Project *-- "4" Time.Phase
Time.Phase *-- "1..*" Time.Iteration
Time.Iteration *-- "1..*" Time.Discipline
Time.Discipline *-- "1..*" Time.Activity

Time.Phase *-- "2" Time.DateRange
Time.Iteration *-- "2" Time.DateRange
Time.Activity *- "2" Time.DateRange

'Resources
Resources.Team *-down- "1..*" Resources.Member
Resources.Member *-- "0..*" Resources.Rol : skills
Resources.Member *-- "1" Resources.JornadaLaboral

'Resources - Time
Resources.JornadaLaboral *-- "*" Time.DateRange : Holidays
Time.Activity ..> Resources.Rol
Time.Activity o-- "1" Resources.Member
@enduml
