@startuml
top to bottom direction
skinparam Linetype ortho

'Time
Phase *- "1..*" Iteration
Phase *- "1" Milestone
Milestone o-- "1" DateRange
Iteration *- "1..*" IterationDiscipline
IterationDiscipline *-- "1..*" Activity

Phase *-- "starts&ends" DateRange
Iteration *-- "starts&ends" DateRange
Activity *-- "starts&ends" DateRange

'Resources
Team *-- "1..*" Member
Member "0..*" o- "0..* skills" Rol
Member *-- DaysOff

'Resources - Time
Activity o-- "required Rol" Rol
Member *-- "0..*" WorkLog
Activity <- "1..*" WorkLog
DaysOff --> DateRange
@enduml
