@startuml
top to bottom direction
title Domain Model RUP Management - Time

Class Time.Project
Class Time.Phase
Class Time.Iteration
Class Time.Discipline

Time.Project *-- "4" Time.Phase
Time.Discipline "1..*" <.. Time.Activity
Time.Phase o- "1..*" Time.Activity
Time.Phase *-- Time.Interval
Time.Phase -- Time.Iteration
Time.Activity *-- Time.Interval
Time.Interval *-- "2" Time.Date

@enduml
